### ISSUE TITLE
Kontostand abgleichen

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#123]
Abgleich zwischen meinem *lamonee-Konto und meinem Kontoauszug: 
stimmen die beiden Dinger überein? Falls nicht, wie groß ist die Abweichung?

**Comment by Tosh79** [comment]
> Beim Bargeld passiert es mir leider sehr häufig, dass beim
> Abgleich der Inhalt nicht mehr stimmt, also Geld fehlt oder zu viel drin
> ist, einfach weil man schnell mal vergisst was einzutragen wenn man
> irgendwo was bar bezahlt oder bekommt. Bei YNAB musste man ja zum
> abgleichen immer den aktuelln Kontostand eintragen und ggf. wurde dann
> ein Betrag zum Ausgleich automatisch von YNAB berechnet. Wie kann ich
> den aktuellen Inhalt des Bar-Kontos in LAmonee ändern?

**Comment by zickzackzuck** [comment]
Genau diese Funktion würde mich auch interessieren und ich glaube sie ist fundamental, da sonst Realität und Budgetplanung auseinanderklaffen.

Zur Zeit verwirrend: Ich lege ein Konto an, mir wird gesagt, ich könne den Kontostand anpassen, aber ich finde diese Anpassung des Kontostands nirgendwo. Gucke ich falsch?

**Comment by Tosh79** [comment]
Hi @zickzackzuck ich weiß nicht, ob Du mir auch eine E-Mail geschrieben hast und ich dort Deine Frage schon beantwortet habe. Deshalb hier noch einmal: Du kannst Deinen initialen Kontostand anpassen, indem Du den Umsatz "Initialer Kontostand" entsprechend bearbeitest. Einfach einen neuen Euro-Wert angeben und schon hast Du einen neuen, initialen Kontostand.

Gruß
Tobias
