### ISSUE TITLE
Sparziel: Mehr Auswahlmöglichkeiten in der Zieldatum-Drop-Down-Box hinzufügen

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#139]
18 Monate?

**Comment by Tosh79** [comment]
Wird in #2 und #287 geregelt.

**Comment by Geda173** [comment]
Moin, wollte jetzt nicht unbedingt ein neues Feld öffnen, aber aktuell ist das Maximum bei 17 oder 18 Monaten für das Sparziel. Gerade bei größeren Ausgaben kann das Ziel auch viel weiter in der Zukunft sein. Wenn ich z.B. eine Summe X bis 2030 zurückgezahlt haben muss, dann muss ich aktuell die Etappen in Einzelteile zerlegen und die Charms dann immer wieder anpassen. Es wäre super das Zieldatum entweder händisch eingeben zu können, oder das Drop-Down-Menü viel weiter in die Zukunft schauen zu lassen.

**Comment by Tosh79** [comment]
Hallo @Geda173 , mit dem nächsten Update wirst Du Sparziele beliebig weit in die Zukunft planen können!

LG
Tobias
