### ISSUE TITLE
Alte Budgetposten archivieren

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#144]
Ungenutzte Budgetposten kann man nur löschen, wenn sie keinen einzigen zugeordneten Umsatz (und auch nix budgetiert?) haben. Alle anderen kann man wohl "archivieren". Sie landen dann in einer "Archiv-Kategorie", die nur sichtbar ist, wenn man's wirklich will...

Könnte auch als Alternativ-Option angeboten werden, wenn der Budgetposten gerade nicht gelöscht werden kann (#599, bzw. #612).

**Comment by Tosh79** [comment]
> nicht mehr benötigte Bugdetposten ausblenden; Ich möchte sie nicht löschen um die Historie nicht zu verlieren, aber so etwas wie abbezahlter Kredit muss in der Liste der Budgetposten nicht mehr auftauchen.

**Comment by Tosh79** [comment]
> Ich würde mich freuen, wenn es die Möglichkeit gäbe, Budgetposten auszublenden. Ich nutze einzelne Budgetposten für konkrete Sparziele (für ein neues Rennrad bspw.) und habe keine Verwendung mehr für den Posten, wenn das Sparziel erreicht ist. 
> Gleiches gilt für Verträge, die ich gekündigt habe, die aber als leerer Budgetposten in meinem Budget weiter leben. Solche würde ich gerne ausblenden können. 
> Derzeit verschiebe ich sie in eine Kategorie &quot;Archiv&quot; am Ende meines Budgets, um sie ein wenig aus dem Blick zu bekommen.

**Comment by Tosh79** [comment]
> kann man Budgetposten, die sich erledigt haben (weil sie für einmalige Anschaffungen waren z. B.), verstecken? Die stören mein Auge. ;-)

**Comment by MarcelErdmann** [comment]
Das wäre eine sehr wünschenswerte Funktion. Bin ich auch schon drüber gestolpert. Löschen ist keine Option da dann auf einem nicht kategorisierte Buchungen auftauchen. Das sollte man beim Löschen auch klarer kommunizieren. Verstecken ist genau das was benötigt wird.

**Comment by Tosh79** [comment]
> Ich habe Kategorien intuitiv anders verwendet, als sie vermutlich
> gemeint sind. Ich hatte z.B. eine Fixkostenkategorie "$Anbieter
> Handyvertrag". Als ich von dem Anbieter weg bin und zu Prepaid
> übergegangen bin, habe ich eine neue Kategorie angelegt und die alte
> gelöscht. Das hat erstmal sämtliche alten Umsätze der Kategorie zerstört
> und ich musste die einzeln manuell anpassen.
