### ISSUE TITLE
Navigation im Umsatzmenü

### ISSUE THREAD

**Issue by ghost** [Tosh79/lamonee_backlog#314]
Wenn ich die Übersicht der Umsätze aufrufe, kann ich nicht einen Monat vor oder zurück navigieren. 
![CBFAE3B7-2C0D-42D2-8624-379352822ADC](https://user-images.githubusercontent.com/64558956/89635744-c5ecf400-d8a7-11ea-9f87-3e42155bebf3.jpeg)

**Comment by Tosh79** [comment]
Guter Punkt!

Du kannst ja über der Umsatzkarte schon die Monatsnavigation erahnen. Wie wäre es, wenn ich genau die bedienbar machen würde?

**Comment by ghost** [comment]
Würde meiner Meinung nach völlig ausreichen.
