### ISSUE TITLE
Umsatzmenu: Kontoauswahl verbessern

### ISSUE THREAD

**Issue by ghost** [Tosh79/lamonee_backlog#315]
![794197E2-9C3B-4544-A1DF-51B071017FE4](https://user-images.githubusercontent.com/64558956/89636143-6e02bd00-d8a8-11ea-91f5-cfd7c557b4cc.jpeg)

Aktuell dauert es sehr lange bis ich an das letzte der sieben Konten komme. Sechs mal wischen ist schon viel. 
Eventuell ein Dropdown-Menü aufzeigen so bald mehr wie drei Konten vorhanden sind oder sonst über ein Click/press auf die Kontobezeichnung eine Navigationsauswahl erhalten.

**Comment by Tosh79** [comment]
Guter Punkt, der gerade bei vielen Konten Sinn macht.

Du kannst ja auch direkt auf die Punkte unter den Karten tippen, um direkt auf ne Karte zu springen - vorausgesetzt, Du weißt, an welcher Stelle Dein Konto liegt.

Hmm... die Karten waren schon ein Eyecatcher... aber vllt. müssen wir doch zu einer Dropdown-Box wechseln.

Ich bin für Vorschläge voll offen!

**Comment by ghost** [comment]
Die Karten gefallen mir auch, keine Frage! Das mit den Punkten ist mir nicht in den Kopf gekommen.

Alternativ, könntest du einen weiteren Slider erstellen auf dem man die Konten managen kann (neues Konto/altes schließen) und auf dem sich die Reihenfolge der Konten per Drag and drop ändern lässt. 
Ändert nur leider nichts an der Kontenauswahl.

**Comment by Tosh79** [comment]
Ich werde mir mal etwas überlegen! Danke für Deinen Input!
