### ISSUE TITLE
Monatsumsätze: Suchfunktion sucht nur das Feld "Empfänger" ab

### ISSUE THREAD

**Issue by ghost** [Tosh79/lamonee_backlog#320]
leider kann ich nicht nach Budgetposten/-kategorien suchen oder nach der hinterlegten Notiz

**Comment by Tosh79** [comment]
Hallo @fazzer4x 

Du kannst tatsächlich nach dem zugeordneten Budgetposten suchen. Siehe hier:

![Desktop2](https://user-images.githubusercontent.com/40628353/90287451-37184280-de78-11ea-93a6-cd7d3b77217f.jpg)

Dafür gibt es sogar einen Shortcut. Klickst Du in der Desktop-Version bei einem Budgetposten auf einen Geldwert der Spalte "Umsätze", wird das Suchfeld automatisch ausgefüllt (siehe #309).

![Desktop](https://user-images.githubusercontent.com/40628353/90287583-6e86ef00-de78-11ea-9154-aeab41f9075c.jpg)

Wenn's diese Funktionen nicht bei Dir gibt, dann führe bitte einmal einen Refresh aus, der auch den Browsercache leert.

Was tatsächlich noch nicht geht, ist eine Suche nach der Kategorie eines Budgetpostens und die Indizierung des Notiz-Feldes. Ersteres würde ich erst einmal außen vor lassen, zweiteres würde ich angehen (siehe #322).

**Comment by ghost** [comment]
Tatsache, die Suche über die Budgetseite funktioniert. Ist mir nicht aufgefallen. Danke 

Auf meinem Handy lässt sich diese Funktion aber leider derzeit nicht nachstellen.

**Comment by Tosh79** [comment]
Hallo @fazzer4x ,

hmm... ich habe es gerade noch einmal auf meinem iPhone getestet. Da tun's beide Funktionen (1. die Suche nach Budgetposten im Textfeld und 2. der Absprung von der Detailansicht eines Budgetpostens bei Tap auf das "Lupe"-Symbol in der Zeile "Umsätze" 

![search](https://user-images.githubusercontent.com/40628353/90322129-a7929280-df50-11ea-8399-4747907cd5ba.jpg)

Es kann sein, dass Du Deinen Safari-Cache einmal leeren musst. Schließe dazu Safari und / oder die PWA von *lamonee (falls Du die Schritte unter https://www.lamonee.de/lamonee-als-app-installieren/ befolgt hast).

Gehe dann in die Einstellung Deines iPhones -> Safari -> Erweitert (gaaanz unten) -> Website-Daten -> (nach *lamonee suchen) -> Swipe nach links auf "lamonee.de" -> wähle "löschen".

Ja, ich werde sehr bald dafür sorgen, dass diese Schritte nicht mehr händisch ausgeführt werden müssen (siehe #327 ).

Funktioniert es dann?

Viele Grüße!

**Comment by ghost** [comment]
Erledigt. Habe die die aktuelle Version ausprobiert und es funktioniert.
