### ISSUE TITLE
Monatsumsätze: Filterfunktion ist festgelegt auf nicht zugeordnete Transaktionen

### ISSUE THREAD

**Issue by ghost** [Tosh79/lamonee_backlog#321]
Toll wäre wenn ich bei dem Filter nach einer Kategorie filtern kann

**Comment by Tosh79** [comment]
Hallo @fazzer4x ,

siehe meine Anmerkungen zu #320 . Das Suchfeld durchsucht auch die zugeordneten Budgetposten. 

Ist damit diese Anfrage hinfällig?

Gruß
Tobias

**Comment by ghost** [comment]
Jein. Meiner Meinung nach impliziert die Formulierung "Gefiltert nach: " das ich hier eine Wahl habe. 
Wenn die Filterfunktion lediglich für die nicht zugeordneten Umsätze ist, möchte ich vorschlagen, dass dort nur "nicht zugeordnete Umsätze" oder ähnlich steht. 
Finde ich persönlich etwas eindeutiger. Wie siehst du das? 

<img width="393" alt="Bildschirmfoto 2020-08-15 um 12 08 05" src="https://user-images.githubusercontent.com/64558956/90310227-fa882d80-deef-11ea-9221-497c8d17378e.png">

**Comment by Tosh79** [comment]
Hi @fazzer4x . Sehr guter Punkt. Ich werde das Naming anpassen. Vielleicht sogar auch das Icon (wenn ich ein passendes finde).
