### ISSUE TITLE
new.lamonee redirect auf https:// 

### ISSUE THREAD

**Issue by ghost** [Tosh79/lamonee_backlog#326]
Wenn ich new.lamonee.de aufrufe, bekomme ich die http version serviert. Kann mich allerdings nicht einloggen und bekomme eine Fehlermeldung. 
Sobald ich aber auf https://new.lamonee.de eingeben, bin ich (auf safari) automatisch eingeloggt. 
Unter firefox muss ich die credentials noch mal eingeben.

**Comment by Tosh79** [comment]
Hallo @fazzer4x. Das sollte natürlich nicht sein. Ich werde mir das Thema ansehen. Danke für die Meldung!

**Comment by Tosh79** [comment]
Ein Update sorgt jetzt dafür, dass *lamonee immer auf HTTPS umleitet, sollte eine HTTP-Anfrage 'reinkommen.

Vielen Dank noch einmal für die Meldung!
