### ISSUE TITLE
neue Empfänger werden nicht direkt vorgeschlagen

### ISSUE THREAD

**Issue by ghost** [Tosh79/lamonee_backlog#334]
Wenn ich Empfänger in lamonee neu anlegen, werden diese bei einer erneuten Eingabe nicht angezeigt. 
Leider erst wenn ich lamonee im Browser komplett neu lade. 

Ist es möglich das die Vorschläge auch so aktualisiert werden?

**Comment by Tosh79** [comment]
Hallo @fazzer4x !

Auf jeden Fal! So war es auch angedacht. Anscheinend hat sich ein kleiner Fehler eingeschlichen. Ich schau's mir an!

Viele Grüße
