### ISSUE TITLE
"Unakzeptiert"-Filter-Button in die Suchleiste verschieben

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#338]
Dann habe ich alle Werkzeuge, um Umsätze zu suchen und zu filtern an einem Ort. Macht total Sinn.

**Comment by Tosh79** [comment]
Ich habe die Änderung wieder zurückgenommen. Sah nicht aus. Hat nicht gut funktioniert. Die Zweiteilung ist "runder".

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/64558956/90681624-fa778d00-e263-11ea-83c9-7a83752043f1.jpeg)

Ist das dann der aktuelle Stand?

**Comment by Tosh79** [comment]
Hallo @fazzer4x ,

nein, das war der alte Stand, mit dem ich nicht zufrieden war. Die "finale" (aka zurückgenommene) Stand ist JETZT live.

Viele Grüße
