### ISSUE TITLE
Nicht zugeordneter Umsatz kann nicht kategorisiert werden

### ISSUE THREAD

**Issue by Saradoc** [Tosh79/lamonee_backlog#367]
Bisherige Vorgehensweise beim Kategorisieren eines nicht umgeordneten Umsatzes (den gesamten April):
- auf den Bereich "nicht zugeordnet"(Bild 1) klicken
- Overlay "Umsatzdetails"(Bild 2) öffnet sich
- dort dann in einem Filtertextfield den Namen der Kategorie eintippen

Wollte mit dem Mai fortfahren, dort erscheint jedoch nicht das Filtertextfield und die Stelle, an welchem es sich befand, ist nun leer (siehe rote Umrandung Bild 2).
Auch die Folgemonate verhalten sich nun so.

-Google Chrome Version 85.0.4183.83 (Offizieller Build) (64-Bit)
-Cookies löschen und andere Browser zeigen das selbe Ergebnis an

![1](https://user-images.githubusercontent.com/70606848/92313527-fae68680-efcc-11ea-8b0d-c32d03054d8a.png)

![2](https://user-images.githubusercontent.com/70606848/92313589-d0e19400-efcd-11ea-9854-24f436ae8a1c.png)

**Comment by Tosh79** [comment]
Hallo @Saradoc und vielen Dank für die Meldung!

Ich habe gerade versucht, das Problem nachzustellen (ebenfalls mit Chrome Version 85.0.4183.83 (Offizieller Build) (64-Bit)). Bei mir wird das Zuordnungs-Feld angezeigt.

Bitte probiere einmal folgendes aus:
- Lade die Seite neu, indem Du STRG und F5 drückst (damit erzwingst Du einen Cache-Reload der Seite. Siehe auch https://support.google.com/chrome/thread/16531954?hl=en). Besteht das Problem dann weiterhin?

Falls ja einige Fragen:
1. Funktioniert die Zuweisung von Budgetposten im April immer noch? Oder ist die Zuweisung jetzt auch dort defekt?

2. Öffne bitte einmal mit dem Tastenkürzel "STRG + SHIFT + I" (großes i) die Chrome-Konsole. Werden Dir dort Fehlermeldungen angezeigt? Sollte eigentlich nicht der Fall sein, eventuell kommt aber doch etwas rein.

3. Solltest Du die Chrome-Devtools wg. Frage 2 noch offen haben (ansonsten kannst Du Einfach F12 drücken). Bitte wechsele auf den Reiter "Network" und drücke dann dort noch einmal F5 (oder STRG + R), um die Seite neu zu laden. Hier siehst Du jetzt die AJAX-Aufrufe, die *lamonee an den Server abfeuert. Wird Dir dort ein Fehler angezeigt?

Ich hoffe, wir kommen dem Fehler auf diese Weise auf die Schliche!

Viele Grüße!
Tobias
