### ISSUE TITLE
Monatsabschlüsse der Budgetposten übertragen

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#369]
> Folgendes: Angenommen am Ende des Monats verbleiben in einer Kategorie noch 7,00 €. Im nächsten Monat budgetiere in selbiger Kategorie 10,00 €. Dann habe ich in dieser Kategorie 17,00 € zur Verfügung. Macht für mich Sinn und ist dahingehend ganz nett, dass man auch in einzelnen Kategorien durch sparen, sparen kann :-)
> Jetzt habe ich es aber einen Monat übertrieben und bin nicht 7,00 € im Plus sondern im Minus. Nächsten Monat budgetiere ich wieder 10,00 € in die Kategorie. Dann habe ich 10,00 € zur Verfügung.
> 
> Für mich ist dieses Verhalten etwas widersprüchlich. Logischerweise müssten entweder sowohl positive wie negative Überschreitungen in den nächsten Monat mitgezogen (wie jetzt nur  bei positivem Übertrag) oder eben immer auf Null gesetzt werden (wie jetzt nur bei negativen Überträgen). Der Quickfix wäre also erstmal die Entscheidung für das eine oder andere.
> 
> YNAB hatte das  auch ganz clever gelöst und hier dem Nutzer die Wahl überlassen. So können die Nutzer etwas monatsunabhängiger agieren und sich trotzdem an das Budget halten. Bspw. den einen Monat etwas überziehen, das dann mit in den nächsten tragen und einfach hier etwas sparsamer leben. Ein weiteres Plus ist auch der Lerneffekt. Nur wenn ich ein Überschreiten (positiv wie negativ) mit in die nächsten Monat mitnehme, sehe ich wie gut meine Zuteilungen funktionieren und kann sie leichter anpassen.

**Comment by Tosh79** [comment]
Mit dabei waren dankenswerterweise zwei Layout-Ideen:
1.) Checkbox in der Bearbeitungsmaske für Budgetposten
2.) Checkbox im Schnellbudget-Menü

**Comment by Tosh79** [comment]
Ich schätze die Komplexität doch eher "hoch" ein. Hätte ordentlich Einfluss auf die Art und Weise, wie *lamonee die Budgets berechnet und muss entsprechend vorsichtig behandelt werden.

**Comment by Tosh79** [comment]
> Die Möglichkeit den automatischen Ausgleich von Budgets abzuschalten (um auch eine negative Entwicklung zuzulassen, also sich bewusst dafür zu entscheiden, das Budget erst im nächsten Monat auszugleichen)

**Comment by Displayfreak** [comment]
> YNAB hatte das auch ganz clever gelöst und hier dem Nutzer die Wahl überlassen. So können die Nutzer etwas monatsunabhängiger agieren und sich trotzdem an das Budget halten. Bspw. den einen Monat etwas überziehen, das dann mit in den nächsten tragen und einfach hier etwas sparsamer leben. Ein weiteres Plus ist auch der Lerneffekt. Nur wenn ich ein Überschreiten (positiv wie negativ) mit in die nächsten Monat mitnehme, sehe ich wie gut meine Zuteilungen funktionieren und kann sie leichter anpassen.

Mir fehlt das Feature auch für folgenden alltäglichen Fall: Ich strecke jemandem etwas vor (der Budgetposten geht in‘s Minus und wird übertragen, bis mir derjenige dies wieder ausgleicht, Budgetposten geht auf null). Das Minus ist für mich die Erinnerung, dass da noch was offen ist. Ich nutze das sowohl für Freunde als auch für meine Arztrechnungen, bis ich diese ich erstattet bekomme.

Hätte ich also auch sehr gerne, so ein Feature.

**Comment by Tosh79** [comment]
Hallo @Displayfreak , vielen Dank für Deine Anmerkung. YNAB hat ja mittlerweile diese Möglichkeit wieder 'rausgeworfen, wenn ich das richtig verstanden habe. Und auch ich habe mich immer schon schwer damit getan, weil's halt einfach gegen "Essenz" dieser Art von Budgetplanung spricht. Weil, long story short, ein negativer Budgetposten ja eigentlich nicht wirklich heißt, dass hier Geld fehlt, sondern dass die Realität von Deiner *lamonee-Planung abweicht, denn Du hast ja bereits den Betrag beglichen, sonst hätten Dein Arzt oder Deine Freunde ja kein Geld gesehen. Du hast nur *lamonee nicht mitgeteilt, aus welchem anderen Budgetposten Du Dich bedient hast. 

Diese "Fehlplanung", bzw. diese Abweichung von der Realität sollte halt schnellstmöglich behoben werden, indem Du Deine Planung anpasst. Machst Du das nicht, macht das *lamonee spätestens zum Monatswechsel für Dich, so dass die Planung wieder der Realität entspricht.

Ich glaube, solche "Reminder", die natürlich total notwendig sind, solltest Du am besten mit der geplanten Notizfunktion á #79  abbilden. Oder was sagst Du?

**Comment by Tosh79** [comment]
> "Ich nutze recht viel die Option "Mehrere Budgetposten". Vor allem in Kombination mit einer Kategorie "Aussenstände". Bsp. ich buche mehrere Hotelübernachtungen für Freunde und mich, rufe dann mehrere Budgetposten auf und trage meinen Anteil in meiner Kategorie "Urlaub" einen und den meiner Freunde in einer Kategorie "Aussenstände". So behalte ich den Überblick für wen ich wann wie mal Geld ausgelegt habe und hab einen Ort, wo ich das Geld dann verbuche, wenn es zurück kommt.
> 
> An der Zahl die ich dort im Moment sehe habe ich meine Zweifel und wollte nachrechnen. Deswegen wollte ich mit der Filterfunktion in Umsätze alle der Kategorie "Aussenstände" anzeigen lassen, mal alles addieren und das nachvollziehen. Ich bekomme zwar einige Umsätze angezeigt, aber eben nicht alle – nämlich nur die, die ich nicht mittels "Mehrere Budgetposten" verteilt habe.
> 
> Du hast recht, die Umsätze werden gebucht, auch wenn sie mit "Mehrere Budgetposten" verteilt wurden. Trotzdem stimmt mein Endwert nicht. Ein neuer Ansatz warum: Ich hab das Problem ja mit meiner Kategorie "Aussenstände". Die nutze ich so, dass sie meistens negativ ist. (Geht ja um Geld, dass mir andere schulden) Der Negativbetrag wird leider nicht mit in den nächsten Monat genommen – wenigstens aber nicht ins nächste Jahr, denn beim Wechsel Dezember / Januar konnte ich das eindeutig so feststellen. Lamonee erlässt quasi mtl. eine Amnestie. Gut für meine Schuldner, schlecht für mich :-)
> 
> Oder gab es irgendwo eine extra Einstellung, um die Mitnahme von Budgetüberschreitungen in den nächsten Monat zu aktivieren. Ich erinnere, dass man in YNAB so etwas aktivieren musste. "

**Comment by Tosh79** [comment]
> "gibt es ne Chance den roten Pfeil aus ynab4 zu bekommen. Daher bei überzogenem Budget einer Kategorie die Summe im nächsten Monat von der gleichen Kategorie abziehen. Ich nutze das bisher stark für meine Reisespesen bei denen ich weiss das ich das Geld in den nächsten 2 Wochen zurückbekomme"

**Comment by Tosh79** [comment]
> Als Nutzer möchte ich in der Lage sein, ein überzogenes Budget in den/die Folgemonat/e mitzunehmen und so aktiv an dem Ausgleich zu arbeiten. Dies kann auch durch ein *charm geschehen, das evtl. sogar automatisch angelegt wird, wenn ich es möchte. (Du hast in diesem Monat 4 Budgets in dieser Kategorie überzogen, möchtest Du einen neuen Ausgleichs-*charm dafür anlegen?)

**Comment by Tosh79** [comment]
> Die meisten Leute budgetieren doch sicher, weil sie im Alltag über ihren Verhältnissen leben. Ich finde es gerade dann wichtig, dass man überzogene Budgets wieder ausgleichen muss. Ich meine, wenn ich einen Monat für 200€ Pizza esse, aber nur 20€ dafür budgetiert habe, sind die zusätzlichen 180€ ja weg. Die fehlen mir dann auf meinem Konto. Dazu braucht man dann irgendeinen Anreiz, dies wieder auszugleichen. Finde ich.
> Ich kann dann entweder 9 Monate lang keine Pizza mehr essen oder aber von meinem Budget für Klamotten-Shopping 180€ umbuchen.

**Comment by cswrd** [comment]
Ich habe mir soeben lamonee angeschaut. Dieses Feature habe ich direkt vermisst. Für mich ist es tatsächlich ein must have. Genau wegen der oben genannten Gründe. Meine 2 Hauptmotivation sind dabei: im Mittel die Ausgaben pro (Sub-)Kategorie zu steuern, sowie die "Schulden ggü. sich selbst" sehen zu können - pro Kategorie. Wenn man z.B. 50€ Lieferdienst plant, aber 70€ ausgibt, ist es für mich sehr wertvoll um dann entweder unmittelbar im nächsten Monat nur 30€ auszugeben oder, sollte das so weiter gehen, ggf. ein paar Monate später das Budget anzupassen (was aufgrund der Inflation ja sowieso immer wieder nötig wird). Ich fahre damit extrem gut.
Bei meiner bisher verwendeten App (everypocket.com - kA wie lange es die noch geben wird) kann man pro Subkategorie die sog. "overspent behavior" einstellen: (1) verfügbares oder überzogenes Budget auf/vom verfügbaren monatlichen Gesamtbudget des Folgemonats dazurechnen/abziehen (2) im Folgemonat der Kategorie abziehen/hinzurechnen (carry-over / rollover)

**Comment by dreuter** [comment]
Erstmal vorab: Danke für diese tolle Software :)
Du hast mich davor bewahrt mich mit irgendwelchen Skripten und Excel Tabellen auseinander setzen zu müssen um mein Budget zu planen.

Für mich ist das auch ein sehr wichtiges Feature.

Ich bin oft geschäftlich unterwegs und muss dann bspw. das Hotel vorlegen. Ich habe dafür ein eigenes Budget. Es lohnt sich für mich aber nicht tatsächlich Geld dafür vorzuhalten, da das Konto durch die anderen Budgets gedeckt ist und ich sicher weiß, dass ich das Geld wiederbekomme, allerdings öfter mal erst im nächsten Monat.

Dann würde ich gerne einfach im Budget sehen, dass noch X Euro offen sind und sobald die Ausgleichszahlung kommt der Wert wieder auf 0 fällt.

Desweiteren habe ich jetzt auch das letzte Jahr durchbudgetiert und könnte dafür ebenfalls dieses Feature gebrauchen.

Alternativ wäre es für mich auch in Ordnung wenn ich bestimmten Buchungen einfach einen anderen Monat zuweisen könnte in dem diese gelten (Ich nehme an, dass wenn ich das Datum ändere dann beim nächsten CSV import alles durcheinander kommt?)

Ich werde mir wohl erstmal so behelfen, dass ich zwei neue Buchungen anlege, die sich dann genau auf null ergänzen, aber mir eben ermöglichen das Geld in einen anderen Monat zu schieben.

Abgesehen davon finde ich das Konzept "sich selbst gegenüber Schulden zu machen" auch ab und zu reizvoll und schön, wenn lamonee das unterstützen würde.

**Comment by Tosh79** [comment]
> was mir gerade beim Monatswechsel aufgefallen ist, negative Budgets werden nicht in den Folgemonat übertragen, das Budget steht dann wieder auf Null. Ist das von Dir so gewollt? Ich fände es sinnvoll, auch negative Budgets auf den Folgemonat zu übertragen, um sie dann dort auszugleichen. Anwendung bei mir: Wenn ich Geld für andere verauslagt habe und es später wieder zurückbekomme.

**Comment by Tosh79** [comment]
Ich habe noch einmal lange darüber nachgedacht und werde das Feature NICHT einbauen. Ich werde das Thema in #735 zu einem Abschluss bringen.

**Comment by Tosh79** [comment]
> Ich habe für eine Dienstreise Geld ausgelegt, welches ich aber erst im nächsten Jahr wieder bekommen werde. Allerdings ergibt es für mich auch keinen Sinn, immer (mehrere) tausend Euro in einem Budget gebunden zu haben, nur damit die Rechnung irgendwie aufgeht (wenn das Geld maximal ne Woche nicht auf dem Konto liegt, aber leider eben oft über einen Monat hinaus). Für genug Kontodeckung ist durch diverse "Sparposten" gesorgt, die niemals alle gleichzeitig in Anspruch genommen werden.
> Ich kann durchaus verstehen, dass es entgegen des Sinnes vom Budgetieren ist, negative Budgetposten zu haben, allerdings gibt es leider diese Auslagensituationen, die mir einfach immer nur das Budget komplett durcheinander bringen. Wollte dir da nur nochmal Feedback zu dem Issue geben. Könnte man so ein Feature nicht hinter genug "Warnungspopups" oder Ähnliches legen, so dass man Neueinsteiger weiterhin zu positiven Budgets "zwingt"?
> Oder gibt es einen anderen Weg, das Ganze abzubilden, ohne reales Geld zu binden (was mir einfach "zu teuer" ist), oder sein Vermögen virtuell aufzublähen (was ich nicht möchte). Ich hab da schon einiges durchprobiert, aber leider nichts gefunden, das für mich funktioniert.

**Comment by Tosh79** [comment]
Hnrgh! Das Feature steht IMMER NOCH ganz oben auf der Wunschliste der Nutzer.

**Comment by Tosh79** [comment]
DONE
