### ISSUE TITLE
Kategorie Details

### ISSUE THREAD

**Issue by ghost** [Tosh79/lamonee_backlog#419]
Die ausklappbaren Kategorie Details 
![image](https://user-images.githubusercontent.com/57394581/96842994-11964f00-144e-11eb-95d6-afff40680076.png)

Sollten nicht nur über das X geschlossen werden können sondern auch wenn man außerhalb dieser in das Fenster klickt.

**Comment by Tosh79** [comment]
Hallo @flammehawk,

ja, das ist so eine Sache mit den Dialogen, die Du quasi auf zweierlei Wegen darstellen kannst. 

- In Variante a) Musst Du den aktuellen Dialog schließen, um im Hauptteil weiterarbeiten zu können. In einem solchen Fall ist es ohne Probleme möglich, das von Dir gewünschte Verhalten umzusetzen.

- In Variante b) Kannst Du auch im Hauptteil weiterarbeiten, selbst wenn der Dialog (in Deinem Fall die Kategorie-Details) offen ist. In diesem Fall ist es quasi unmöglich, das von Dir gewünschte Verhalten umzusetzen.

In Sachen Kategorie- und Budgetposten-Details habe ich mich dazu entschieden, die Dialog entsprechend Variante b) umzusetzen? Der Grund: auf diese Weise kann der Nutzer schnell von der Detailansicht eines Postens / einer Kategorie zur Detailansicht eines anderen Postens / einer andere Kategorie wechseln, einfach indem er einen anderen Posten / eine andere Kategorie anklickt. 

Hätte ich die Dialog wie in Variante a) umgesetzt, müsste ich erst den Dialog wegklicken, um mir die Detailansicht eines anderen Postens / einer anderen Kategorie anzusehen. Und ich wollte Klicks sparen.

Deshalb wird das von Dir gewünschte Verhalten eher nicht umgesetzt.

Viele Grüße
Tobias

**Comment by ghost** [comment]
Gut dann ist es wohl ein Bug.
Ich verstehe die Varianten vollkommen, aber damit Variante B zugreift muss man in der Lage sein Selbst mit geöffneten Kategorie Details ungestört weiter arbeiten zu können dies ist aber Momentan nicht der Fall. 
Öhne geöffneten dialog:
![image](https://user-images.githubusercontent.com/57394581/97403787-59f1b900-18f5-11eb-939f-a6d1da20fc43.png)
Mit geöffneten Dialog:
![image](https://user-images.githubusercontent.com/57394581/97403937-91606580-18f5-11eb-8070-c3d799008b3d.png)
Mit geöffneter Monatsübersicht:
![image](https://user-images.githubusercontent.com/57394581/97404031-ba80f600-18f5-11eb-8783-cf8fcc669048.png)

Wie man in den Screenshots erkennen kann ist es bei geöffneter Monatsübersicht möglich ohne Probleme weiter zuarbeiten.
Bei geöffneten Kategorie Details wird: 
1. ein teil des Budgets überlagert
  * Man sieht das Monatsbudget nicht mehr
2. man hat keine möglichkeit das Monatsbudget zu öffnen

Diese Probleme würden nicht auftreten wenn beide Dialoge wie in #422 von dir erwähnt im selben Container liegen würden. Dies ist aber leider nicht der Fall die Kategorie Details liegen im Folgendem Container
```HTML
<div tabindex="-1" class="q-dialog__inner flex no-pointer-events q-dialog__inner--minimized q-dialog__inner--right fixed-right items-center"> {{Content}} </div>
```
Während das Monatsbudget im folgenden Container liegt: 
```HTML
<div class="q-drawer-container">
<aside class="q-drawer q-drawer--right q-layout--prevent-focus q-drawer--standard fixed" style="width: 400px; top: 66px; transform: translateX(400px);">
{{Content}}
</aside>
</div>
```

Und nach etwas rumschauen ist das Problem eher das beim öffnen des Monatsbudgets `padding-right: 400px;` erhällt.
Dieses wird aber nicht gesetzt wird wenn mann die Kategorie Details öffnet.

**Comment by Tosh79** [comment]
Hallo @flammehawk,

nee, das ist tatsächlich kein Bug. Aber auch nicht "working as intended". Ich bin komischerweise davon ausgegangen (warum auch immer), dass der rechte "Drawer" mit den Budget-Details in der Regel ausgeklappt ist. In diesem Szenario schieben sich, wie Du's schon richtig beobachtet hast, die Kategorie- und Budgetposten-Details eben NICHT über die Listenansicht. 

Wenn das Ding aber zu ist, leider wohl und das ist, auch das hast Du richtig beobachtet, Grütze!

Deshalb würde ich das Thema gerne in #422 fortführen.

Danke und Gruß
Tobias
