### ISSUE TITLE
UI: Desktop optimieren

### ISSUE THREAD

**Issue by ghost** [Tosh79/lamonee_backlog#422]
Wenn man das Monatsbudget geöffnet hat.
![image](https://user-images.githubusercontent.com/57394581/96846415-2bd22c00-1452-11eb-89ff-0b2dc851c784.png)

und dann auf die Kategorie klickt für die Details überlagern diese nur das Monatsbudget.
![image](https://user-images.githubusercontent.com/57394581/96846461-3d1b3880-1452-11eb-8074-25cfed590aa5.png)

Dies ist ziemlich unschön in meinen Augen Entweder beides sollte in den selben Container oder die Kategorie Details gehen dann von dem Monatsbudget aus nach Links.

**Comment by Tosh79** [comment]
Hallo @flammehawk,

im Grunde sollten beide Element exakt aufeinanderpassen, so dass, ignoriert man jetzt einmal die Animation der Eindruck entstünde, beide Elemente befänden sich im selben Container. Jetzt sehe ich in Deinem dritten Screenshot einen wirklich unschönen Versatz. 

Mal losgelöst davon, ob Du diesen Versatz meintest oder eben nicht: welchen Browser und welches OS hast Du im Einsatz?

**Comment by ghost** [comment]
Gude, 

Browser im Einsatz ist 
![image](https://user-images.githubusercontent.com/57394581/97403303-78a38000-18f4-11eb-9813-4fa5cce22346.png)

und OS ist Windows 10 version 2004 (build 19041.5752)

**Comment by ghost** [comment]
Und nein ich meinte nicht diesen versatz der ist dadurch entstanden das ich den Screenshot gemacht habe als die Animation noch am Laufen war.

**Comment by Tosh79** [comment]
Wie ganz richtig in #419 angemerkt ist das Verhalten nicht ganz konsistent. Einige Dialoge, die von rechts kommen, legen sich über den Haupt-Contentbereich (bspw. Kategorie- und Budgetdetails). Einige schieben ihn zusammen (Gesamtbudget-Details). Das muss konsistenter werden!

**Comment by ghost** [comment]
Hierbei wäre es mir persöhnlich am liebsten wenn es entsprechend für jede seite eine ein und ausfarbare sidebar gibt. 
Über die man dann per Arkordeon oder ähnliches dann zwischen Monatsbudget,  Kategoriedetails und Postendetails wechseln kann. Und man dann nicht großartig die Maus rumschubsen muss um sich etwas anderes anzuschauen. 

Desweiteren  wäre es praktisch in meinen Augen wenn die Kategorie Details nur dann aufgehen wenn man auf einen "Button / Icon" Details klickt.
Genauso würde ich hier erwarten das ich über die gleiche Schaltfläche über die einen dieser Sidecontainer öffne diesen auch wieder schließen kann.  Also folgendes Icon bei den Budget Posten zum aufklappen der Details.  
![image](https://user-images.githubusercontent.com/57394581/98212304-acf5ec80-1f43-11eb-9c90-e6d9417bd36b.png) 
Icon dreht sich um und beim erneuten klick werden die Details wieder geschlossen.


Wenn ich auf den Kategorie Header klicke würde ich erwarten das sich diese zusammenklappt wie bei einem Arkordeon siehe hierfür auch #298  

Genauso wäre in meinen Augen auch ein "Nice To Have" das man die Kategorien die wie eine Tabelle dargestellt werden auch Sortieren kann.

**Comment by Tosh79** [comment]
Das haben wir gemacht...!
