### ISSUE TITLE
ING-Importer: Währungsformat aktualisieren=

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#462]
> Beträge wie 68,10€ werden in der ING-CSV als 68,1 ausgegeben. Lamonee interpretiert das dann aber als 6,81€ (vermutlich einfach fix zwei Nachkommastellen?

ich frage noch einmal nach, ob die CSV-Datei irgendwie händisch angepasst wurde!

**Comment by Displayfreak** [comment]
Bei mir ging das Importieren per CSV mit der ING ohne Probleme (gestern).

**Comment by Tosh79** [comment]
Hi und danke für den Kommentar. Da ich vom ursprünglichen Nutzer kein Feedback erhalten habe und es bei mindestens einem anderen Nutzer funktioniert, schließe ich jetzt dieses Ticket.
