### ISSUE TITLE
Mobile Version: "Budget sortieren" - Option fehlt

### ISSUE THREAD

**Issue by ghost** [Tosh79/lamonee_backlog#479]
Servus, ich mal wieder. 

Ich wurde mich über die Möglichkeit freuen bestimmen zu können in welcher budget Kategorie ein externes konto angezeigt wird. 

Ich war sehr überrascht als ich festgestellt habe das in meiner wishlist aufeinmal mein depot zu finden war und mobile kann ich ihn zumindestens nicht wo anders zu ordnen.

**Comment by Tosh79** [comment]
Hallo @flammehawk,

huppsa! Du hast vollkommen recht! Anscheinend hat mein letztes Update die Option gekillt, auf mobilen Endgeräten das Budget neu zu sortieren. Sorry! Das baue ich so schnell wie möglich wieder ein. 

Alldieweil kannst Du Dein Budget in der Desktop-Version neu sortieren! Klicke dazu einfach oben rechts auf das Symbol neben dem Zahnrad.

Danke für die Meldung!
Tobias
