### ISSUE TITLE
unverified trotz verification mail, erneut senden funktioniert nicht

### ISSUE THREAD

**Issue by fabiovogt** [Tosh79/lamonee_backlog#480]
Habe mich registriert und die Aktivierungsmail bekommen, link geklick. 

Danach habe ich auf dem ersten screen den unteren Button geklickt (Standard Budget laden, oder so!?). Wenn ich nun versuche einen Wert einzugeben, z.b. Miete, kommt unten die Meldung "Es gab Probleme bei der Speicherung der Änderungen." und ich werde auf https://app.lamonee.de/#/unverified weitergeleitet.

Eine erneute Aktivierungsmail wird angeblich versendet, kommt aber nicht an. 

Logout, Login bringt keine Besserung

Chrome Version 80.0.3987.132 (Offizieller Build) (64-Bit)
MacBook Air 2014

**Comment by Tosh79** [comment]
Frohes neues Jahr @fabiovogt,
vielen Dank für die Meldung Deines Problems. Diese "unveridied"-Meldung kommt leider vereinzelt vor und ich bin leider nicht in der immer in der Lage, das Verhalten zu reproduzieren. Deshalb eine ganze Fragenbatterie an Dich:

- hast Du zwischen Deiner erstmaligen Registrierung und der Anlage des Budgetpostens Dein Endgerät oder Browser gewechselt (bspw. auf dem Handy registriert und verifiziert, dann auf dem MacBook eingeloggt und das Budget angelegt)?
- Speicherst Du Cookies? Oder hast Du einen restriktiven Cookie-Blocker drin?
- Surfst Du im privaten Modus?

Das sind einfach ein paar Parameter, die mir dabei helfen sollen, dem Bug (denn das ist es auf jeden Fall) auf die Schliche zu kommen.

Bis dahin solltest Du den Fehler aus der Welt räumen können, indem Du den Website-Cache UND alle *lamonee-Cookies löschst. Besuche dazu https://app.lamopnee.de, klicke dann auf das Schloss-Symbol in Deiner Browser-Adressleise (müsste direkt vor der Adresse angezeigt werden), wähle dann "Website-Einstellungen" und dann in dem Popup "Daten löschen". Du musst Dich dann neu anmelden und alles sollte wie erwünscht funktionieren.

Sollte das nicht zu dem gewünschten Ergebnis führen: bitte besuche https://app.lamonee.de im privaten Modus, logge Dich und versuche dann einmal, einen Budgetposten anzulegen.

Ich hoffe, dass diese Schritte Dich weiterbringen und freue mich auf Deine Antwort!

Gruß!
Tobias

**Comment by fabiovogt** [comment]
Leider hat weder die erste Idee noch der private Modus eine Lösung gebracht. :(
Wenn du es über Teamviewer mal selbst sehen willst, sag Bescheid.

**Comment by Tosh79** [comment]
Hallo @fabiovogt,

ja Mist! Das ist natürlich sehr ärgerlich. Sehr gerne nehme ich Deine Einladung für 'ne Teamviewer-Session an. Sollen wir alles Weitere per E-Mail regeln? Schick' mir einfach eine E-Mail an hallo@lamonee.de. Ich könnte bspw. heute Nachmittag gegen 17:30 Uhr (oder in einer Viertelstunde).

LG
Tobias

**Comment by Tosh79** [comment]
Das Problem wurde behoben (Background: neu registrierte Nutzer hatten automatisch ein Abo-Ende von 31.12.20 eingetragen. Damit kann man leider nix mehr im Januar 2021 anstellen ;-).
