### ISSUE TITLE
Kategoriesummen wieder zurückbringen?

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#535]
Wurde direkt nach dem Update, das die Summen rausgeschmissen, wieder angefragt. Vielleicht war ich da etwas zu voreilig?

**Comment by Tosh79** [comment]
Also definitiv noch ein Thema! Sollte per Option konfigurierbar sein. Idealerweise diese Optionen anbieten:

- Nie anzeigen
- Immer anzeigen
- Nur anzeigen, wenn die Kategorie eingeklappt ist

**Comment by dreuter** [comment]
Ich wollte gerade ein Ticket schreiben, dass so eine Funktion wirklich schön wäre. Schade, dass das Feature rausgeflogen ist.

Da es ja im Moment kein Pie- oder Flamechart gibt, welches einem die Budgetierung visualisiert wären diese Summen für mich sehr hilfreich um mal ein Gefühl dafür zu bekommen welche Bereiche meines Lebens wie viel von meinem Gesamtbudget fressen, ohne jedes mal den Taschenrechner rauskramen zu müssen.

Ich hab lamonee auch gerade meiner Freundin gezeigt und sie hat mich auch gleich danach gefragt :D

**Comment by Tosh79** [comment]
Hallo @dreuter ,
verzage nicht! Mit dem neuesten *lamonee Update, das in den Startlöchern steht, kannst Du über die Kategoriennamen hovern und bekommst dann wieder die Kategoriesummen angezeigt. Und Dein Bedürfnis nach Pie-Charts sollte dann auch vollends befriedigt sein ;-)

**Comment by dreuter** [comment]
Das sind tolle Aussichten :) Vielen Dank!
