### ISSUE TITLE
Reports: Gesamtvermögen über die Monate

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#541]

**Comment by cassava** [comment]
Das würde mich u.U. sehr interessieren. Was auch richtig cool wäre, ist wenn man den höchst und niedrigst-Stand für einen gewissen Zeitraum einsehen könnte. (Brauch ich weil die Amerikanische Regierung darauf besteht es zu wissen für alle Amerikanische Staatsbürger... für jedes Konto...)

**Comment by Tosh79** [comment]
Hallo @cassava , das ist ja mal eine abgefahrene Anforderung der USA. Vielen Dank für die Idee. Werd' ich bei der Integration des Reports berücksichtigen...
