### ISSUE TITLE
Zentraler Kontoimport mit autom. Auswahl des richtigen Kontos

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#555]
Auch eine Nutzeridee:
Ohne vorher ein Konto auszuwählen, starte ich einen Import-Vorgang. *lamonee ist dann clever genug, das Format der CSV-Datei zu erkennen und das richtige Zielkonto für den Import auszuwählen. Sind viele Wenn's und Aber's dran, aber die Idee ist prinzipiell ziemlich reizvoll.

Edit: könnte eine Erweiterung von #795 sein.

- Wenn das Konto nicht erkannt werden konnte, bzw. keines der bekannten Konten das Import-Format unterstützt, sollte *lamonee anbieten, ein neues Konto anzulegen. Flow dann analog #792 .

**Comment by cassava** [comment]
Ich nehme an, dass gilt nachdem die Konten schon eingerichtet sind. Dann muss man nur auswählen zwischen den Konten, die es schon gibt.

Problem: wenn dies funktionieren soll, dann muss es für alle unterstütze Banken funktionieren, denn es könnte jede Kombination vorhanden sein. Die Vorauswahl hilft, schließt aber nichts aus.

Möglichkeit 1:
- HashMap von Header <-> Liste von möglichen Banken
- Für ein CSV wird die Liste dann gefetcht
- Gefiltert nach den schon eingerichteten Konten
- Falls es mehr als eine Möglichkeit gibt, muss der Nutzer dann auswählen

Der letzte Punkt wird immer notwendig sein, denn ich kann ja mehrere Konten von der gleichen Bank haben.

**Comment by Tosh79** [comment]
Hallo @cassava , ja, so charmant ich diese Idee finde... ich glaube, es könnte durchaus kompliziert sein, diesen "Workflow" im laufenden System aufrecht zu erhalten. Aber es ist auch nicht wirklich unmöglich - ich müsste aber mal abwägen, wie viele Nutzer eine solche Funktion wirklich nutzen würden...

Wofür ich diese Funktion aber jetzt einmal in jedem Fall evaluiere, ist das Ticket #570 . Das könnte sehr gut für einen Initialimport funktionieren....

**Comment by cassava** [comment]
Wenn ich es verwenden würde, dann wahrscheinlich nur in Verbindung mit einem "Massenimport":
1. Auf allen Webseiten gehen, Export durchführen
2. Bei *lamonee alle CSVs auf einmal importieren

Ansonsten würde ich eher andere Funktionalität bevorziehen. :-)

**Comment by Tosh79** [comment]
Hi @cassava , dann wäre Deine Anforderung, nicht nur eine CSV-Datei auf's Upload-Feld ziehen zu können, sondern direkt ALLE? Interessant - daran hatte ich noch gar nicht gedacht. Ich war jetzt tatsächlich eher bei MoneyMoney, Outbank und YNAB, die Dir direkt alle Umsatzdaten all dort gepflegter Konten in einem Rutsch ausspucken... aber sehr interessanter Gedanke! Behalte ich im Hinterkopf, wenn ich mir hier dran setze!

LG
Tobias

**Comment by Tosh79** [comment]
Nachdem ich die anderen Tickets des Meilensteins "Importer optimieren" umgesetzt habe, sehe ich gerade wenig Handlungsbedarf. Wenn ich das hier integriere kommt ein ordentliches Stück Unsicherheit nach *lamonee: "Importiert der das jetzt wirklich in das richtige Konto?". Hatte es bereits getestet und es fühlt sich irgendwie nicht gut an. Ich lasse es erst einmal draußen.

**Comment by Tactticus** [comment]
Schade, dass es wohl nicht kommt. Aber keine schlechte Idee.

**Comment by Tosh79** [comment]
Das funktioniert mittlerweile fast genau so. Man muss nur das Konto auswählen. Aber das ist ja sowieso obligatorisch…!
