### ISSUE TITLE
Einkommensabhängige Sparpläne

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#557]
> Bin gerade ein bisschen am herumspielen, gibt es die Möglichkeit Fixkosten abhängig vom Einkommen zu machen?
> 
> -> Interessant für IGM Beitrag

**Comment by cassava** [comment]
Fänd ich auch nützlich zu haben, z.B. wenn man vorgenommen hat, 10% vom Einkommen immer zu sparen, spenden, oder sein Spaßbudget zuzuweisen.

- Einfach zum Zeitpunkt wo man es "festmacht" vorschlagen.
- Wenn nachher noch was hinzukommen sollte, dann bleibt die gebudgete Menge unverändert.

**Comment by Tosh79** [comment]
Ja, so etwas ähnliches hatte ich auch schon einmal überlegt (vgl. die "Einrütteln"-Funktion). Ich hatte da an einen dicken "Restbudget automatisch verteilen"-Button gedacht, den man womöglich sogar mit Regeln belegen könnte... aber das ist tatsächlich aktuell eher Zukunftsmusik - wenn auch ganz attraktive.

**Comment by Tosh79** [comment]
https://github.com/Tosh79/lamonee_backlog/discussions/834
