### ISSUE TITLE
Pricing-Option evaluieren: Lifetime-Membership

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#559]
Was müsste das kosten? Was passiert bei der etwaigen Einstellung von *lamonee?

**Comment by metabubble** [comment]
I.d.R sehe ich irgendwas zwischen 3,5 und 5 Jahre der monatlichen Kosten bei anderen Apps, allerdings habe ich keine dieser apps so lange genutzt. Zero based budgeting allerdings betreibe ich schon seit fast 10 Jahren - aber so lange wird sich keiner binden wollen...

Wenn die Infrastrukturkosten niedrig sind, dann könnte ich mir 100 oder 150€ vorstellen, allerdings als limited offer, um jetzt einen Schwung Geld von den Early adoptern abzuholen. Langfristig ist es vermutlich schlecht für das Geschäftsergebnis.

**Comment by Tosh79** [comment]
So sehe ich das auch. Das Thema ist erst einmal vom Tisch, weil sonst auch niemand mehr danach gefragt hat.
