### ISSUE TITLE
Umsatzzuordnung: Möglichkeit schaffen, einen neuen Budgetposten anzulegen

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#565]
> Im gleichen Prozess haette ich erwartet, dass ich eine neue Kategorie fuer eine Ausgabe direkt im gleichen Fenster erstellen kann. Das kostet zur Zeit allerdings etliche Klicks und dafuer muss man den Vorgang mit der Umsatzzuweisung abbrechen.

**Comment by cassava** [comment]
Gerade am Anfang könnte sowas nützlich sein, wenn man seine ganze Kategorien noch erstellt.
Nachdem alles eingependelt ist, will man gleichzeitig vermeiden, dass man aus Versehen eine neue Kategorie erstellt.

**Comment by Tosh79** [comment]
Hallo @cassava , yes, da bin ich Deiner Meinung. Gerade der "Onboarding"-Prozess von *lamonee ist noch optimierungswürdig. Da wäre eine solche Funktion natürlich echt nett.... könnte man ja gaaaanz unten in der Liste hinzufügen und auch dafür sorgen, dass das Ding nicht per Suche-Funktion gefunden wird. Dann könnte man Fehleingaben verringern.

**Comment by Tosh79** [comment]
Dieses Feature wird in den Tickets #9 (Desktop via Drag & Drop), #630 (Mobil, bestehende Umsätze) und #647 (Mobil, neue Umsätze) integriert. Deshalb kann ich das Ticket hier schließen.
