### ISSUE TITLE
Evaluieren: YNAB-Importer

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#570]
Ich habe einen Testexport via Reddit erhalten. Prüfen.

**Comment by jonathanlang** [comment]
in Anbetracht der Tatsache, dass YNAB selbst Monate gebraucht hat, um einen mehr schlecht als recht funktionierenden Importer für das Classic YNAB zu bauen, ist das wahrscheinlich ein Himmelfahrts-Kommando. Aber wenn es klappen würde fände ich das spannend :)

**Comment by Tosh79** [comment]
Hallo @jonathanlang , ja, "Himmelsfahrtskommando" trifft es ganz gut. Ich muss vor allen Dingen noch einmal prüfen, inwieweit sich das Kosten-Nutzen-technisch lohnt. YNAB4 spielt immer weniger eine Rolle. Wenn ich da jetzt 2-4 Wochen Arbeit reinstecke, um dann 4 Nutzer zu gewinnen, von denen dann nur 1 bleibt... hätte ich besser ein anderes Feature entwickelt :D

**Comment by cassava** [comment]
Es gibt ja auch noch das neue YNAB. Da kann man auch ein CSV Export machen.

**Comment by Tosh79** [comment]
Hallo @cassava , ach, das hatte ich überhaupt nicht auf dem Schirm. Da ich nicht bei nYNAB bin. Care to share einen halbwegs unverbindlichen Export wie unter https://www.lamonee.de/unterstuetzte-banken/ beschrieben? Dann könnte ich mir das mal ansehen....!

**Comment by cassava** [comment]
Nach dem Export bekommt man eine ZIP mit 2 Dateien:

- `Budget Name Datum - Budget.tsv`  
  Hier gehts um die Budget-Kategorien: [Budget.txt](https://github.com/Tosh79/lamonee_backlog/files/7496335/Budget.txt)
- `Budget Name Datum - Register.tsv`  
  Hier gehts um die Umsätze: [Register.txt](https://github.com/Tosh79/lamonee_backlog/files/7496337/Register.txt)

Ich fands nicht so einfach die Datein zu vereinfachen. Hab die Zahlen auch ein bisschen verändert.

Ein paar Anmerkungen:

1. Datum und Währung steht wirklich so drin. Das kann man bei nYNAB selber auswählen, und scheinbar nehmen sie das in dem Export das, was man selber ausgewählt hat. D.h. es wird weitere Formate dafür geben.
2. Tabs werden verwendet (zumindest *hier*), weil wir für die Zahlen ein Komma "," ausgewählt haben. Ich weiß nicht, ob es für Punkt "." anders wäre.
3. Datum in Zukunft ist, was regelmäßig ist. Turnus hab ich aber nicht erkennen können.
4. Transfers zwischen Kontos sind auch in der Liste dabei, aber nicht in meinem Ausschnitt hier.
5. Es sind alle Transaktionen dabei von Anfang bis Ende.
6. Ich weiß gerade nicht, wie "Split Transactions" aussehen.

Um ein gutes Import von YNAB Export hinzubekommen, wirst du wahrscheinlich viel mehr Daten benötigen. Vielleicht ist es geschickter, ein Probemonat oder sowas bei denen zu machen um alles ausprobieren zu können.

**Comment by cassava** [comment]
Ich sollte vielleicht noch dazu sagen, dass ich nicht weiß ob ich *selber* von YNAB tatsächlich importieren würde... Aber wenns wenig Arbeit ist, dann wäre es schon interessant.

**Comment by DMaendlen** [comment]
Ich bin gerade dabei, den Umstieg von YNAB händisch durchzuführen. Gar nicht mal so geil, ein Importfeature wäre schon ziemlich cool.

Demnächst dürfte eine Wechselwelle von nYNAB anstehen, die haben eben erst die Preise erhöht - von einer vorher schon eher unverschämt teuren App zu noch teurer war vermutlich nicht so schlau.

**Comment by Tosh79** [comment]
Hi @DMaendlen , 
jau, ich glaube, ich bin schon mitten in der Wechselwelle drin, wenn ich mir aktuell ansehe, wie meine wöchentliche Registrierungsrate nach oben schnellt :D. Deshalb ist der YNAB-Importer für mich auch aktuell Top-Prio!

LG
Tobias

**Comment by Tosh79** [comment]
> YNAB Importer (damit man Budgetposten nicht abtippen muss)
