### ISSUE TITLE
Kontoanlage:: Datum des initialen Kontostands selber wählen lassen?

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#58]
>  Danke für die schnelle Umsetzung! In der Euphorie den Import zu testen, habe ich meinen Account zurück gesetzt. 
> 
> Nun ist mir beim Erstellen eines neuen Kontos aufgefallen, dass ich nichts von vorher importieren kann.
> 
> Habe dazu deine Release-Notes vom Dezember gelesen. An sich keine schlechte Idee und macht die Sache für viele sicher bequemer. Ich würde allerdings auch gerne vergangene Transaktionen importieren. Zum Beispiel durch das Setzen des Datums des initialen Kontostands.

**Comment by Tosh79** [comment]
Und noch jemand: 

> Hm, ich wollte noch einmal frisch starten und meinen Verlauf übernehmen, aber man kann Konten nicht zurückdatieren, sehe ich das richtig? Nur am Tag des Anlegens kann ein Konto starten? Das ist etwas schade… Warum nicht den Initial-Tag festlegen lassen für diejenigen, die vielleicht etwas Historie mitnehmen möchten?

**Comment by Tosh79** [comment]
Und noch jemand.

**Comment by ghost** [comment]
Mir ist derzeit nicht ersichtlich, wie man bei dem neuen lamonee ein neues Konto anlegt. Hab ich da was übersehen?

**Comment by Tosh79** [comment]
Hallo @fazzer4x ! Nein hast Du nicht, die Funktion ist schlicht noch nicht da. Siehe hierzu https://www.lamonee.de/das-neue-lamonee/ im Abschnitt "_Bitte beachte dabei noch folgende wichtige Anmerkungen_". Wird selbstverständlich zeitnah nachgeliefert.

**Comment by Tosh79** [comment]
Notiz an mich:
"Das Problem ist nicht, dass die Nutzer das Datum des initialen Kontostands selbst aussuchen wollen. Das Problem besteht darin, dass Nutzer schlicht Umsätze importieren wollen, die VOR dem Datum des initialen Kontostands liegen. Jetzt nur die Datumswahl des initialen Kontostands zu erlauben ist unnötig kompliziert (für den Nutzer) und verbessert nicht wirklich dessen UX.

Deshalb sollte ich evaluieren:
- Datum des initialen Kontostands bleibt der Anlagetag des Kontos.
- Der initiale Kontostand kann nicht gelöscht, wohl aber bearbeitet werden.
- Der initiale Kontostand dient als "Fixstern" für das Konto, sollte der Nutzer Umsätze VOR diesem Datum importieren oder anlegen wollen, so muss *lamonee dafür sorgen, dass sich am Kontostand nichts ändert.

**Comment by Tosh79** [comment]
So machen wir es NICHT! Nach eingehender Recherche läuft's wie folgt:
- Datum und Höhe des initialen Kontostands sind Attribute des Bankkontos.
- Macht die Sache eindeutiger. Der Nutzer kann dann Datum und Höhe des initialen Kontostands selbst händisch anpassen.

-> Zu klären:
- Wie für Abwärtskompatibilität sorgen?
- Wie für die Migration ins neue System sorgen?
- Was passiert, wenn ich Transaktionen anlegen will, die VOR diesem Datum liegen?
