### ISSUE TITLE
Evaluieren:: Auto-Refresh alle 15 / 30 / 60 Sekunden?

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#581]
Aktuell gibt's ja "nur" ein Pull-To-Refresh. Womöglich sollte ich das um eine Auto-Refresh-Funktion ergänzen. Siehe Nutzeranfrage:

> Meine Desktop-Webseite aktualisiert nicht automatisch, wenn ich z.b. mit 
> dme Handy eine änderung vornehme. Ist es ein Problem, wenn ich mit 
> mehreren Geräten gleichzeitig zugreife?

**Comment by metabubble** [comment]
Oder per events über einen Websocket? Ist schwerer zu implementieren, aber sollte die Last geringer halten.

**Comment by cassava** [comment]
Was meine Frau und ich oft machen, gleichzeitig auf zwei PCs Umsätze eintragen und zuordnen. Wenn das flüssig ginge, wäre natürlich super!
