### ISSUE TITLE
MoneyMoney Integration

### ISSUE THREAD

**Issue by jonathanlang** [Tosh79/lamonee_backlog#600]
MoneyMoney bietet ein tolles, recht unbekanntes Extension Framework an. Beispielsweise nutze ich für den komfortabelsten Export ever dieses [Plugin](https://github.com/krachtstefan/moneymoney2ynab).

Transaktionen markieren, rechtsklick, "Umsätze an YNAB 4 senden" auswählen, und schon öffnet sich YNAB mit der Konto-Auswahl. 
Würde vermutlich so etwas wie #555 erfordern, selbst wenn es nicht automatisiert ist, aber die Möglichkeit das CSV rüber zu werfen und eine Auswahl des Kontos manuell treffen zu können wäre Voraussetzung.

**Comment by jonathanlang** [comment]
Hm, nevermind, ich sehe gerade, dass die Extension etwas anderes macht, dann scheint die Unterstützung von YNAB in MoneyMoney wahrscheinlich doch von Haus aus mit zu kommen. Ich werde mal den MoneyMoney Entwickler fragen ob sich so etwas auch mit der Extension API realisieren ließe...

**Comment by Tosh79** [comment]
Sieht aber trotzdem ziemlich cool aus! Bin gespannt, ob sie sich MoneyMoney-Menschen melden!

**Comment by jonathanlang** [comment]
Der großartige Support von MoneyMoney hat sich dann doch recht schnell zurück gemeldet, die Verzögerung entstand durch mich: 
Es ist tatsächlich über die Extension-Architektur möglich, hier die[ relevante Seite zur Doku](https://moneymoney-app.com/api/export/). 
Folgende Info hat mir der Entwickler noch zukommen lassen für das YNAB Beispiel: 
Exporter{version          = 1.01,
        format           = "YNAB 4",
        fileExtension    = "qif",
        bundleIdentifier = "com.ynab.YNAB4.LiveCaptive",
        hidden           = true,
        reverseOrder     = false,
        description      = string.format(MM.localizeText("Send transactions to %s"), "YNAB 4")}

Die wesentlichen Parameter sind bundleIdentifier und hidden.

Wenn ich die Doku beim Überfliegen richtig verstehe, erzeugt das Exporter Plugin ein File im richtigen Format, und öffnet die App und wirft das File im Hintergrund rüber. Also müsste Lamonee vermutlich lernen, was passiert wenn man eine CSV Datei beim Öffnen der App mitgibt.

**Comment by Tosh79** [comment]
Tolle Idee für das "erweiterte Backlog" (https://github.com/Tosh79/lamonee_backlog/discussions/834)

**Comment by Tosh79** [comment]
Hallo @jonathanlang ,
vielen Dank für die tolle Idee in dem erweiterten Backlog.. Wie Du siehst, räume ich gerade das Backlog ein wenig leer, damit ich "actionable" bleibe. Bei knapp 200 Backlog-Items war das nicht ganz so einfach. Alle anderen Themen sammele ich jetzt hier (s.u.). Das bedeutet mitnichten, dass sie abgeschrieben sind.
