### ISSUE TITLE
Umsatz: Empfängernamen kürzen

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#603]
Sagen wir mal, wir haben einen Empfänger mit dem Namen "Bäckerei Schmitz GmbH & Co. KG". Wenn ich jetzt probiere, den Namen in "Bäckerei Schmitz" zu ändern, dann schlägt die Auto-Complete-Funktion mit voller Härte zu und ändert den Empfänger wieder zu "Bäckerei Schmitz GmbH & Co. KG". Da muss ich mal schauen, wie gut ich das Problem lösen kann.

**Comment by cassava** [comment]
Ich finde auch, dass die Namen die aus dem Kontoauszug (CSV) kommen, häufig ziemlich unleserlich/hässlich.
Statt "Kaufland Neckarsulm//Neckarsulm/DE / KAUFLAND" reicht mir ja "Kaufland" und am besten immernoch "Kaufland" ob es in Neckarsulm ist oder in Hamburg.

Aber: wer will das schon per Hand machen? Ich jedenfalls nicht. 
YNAB hat ja *Payees* und auch die Möglichkeit, diese zu managen, hauptsächlich: umbennen, mergen.
Vielleicht könnte man auch ein "Zeigen als" Funktion implementieren, sodass man festlegen kann, das "Kaufland Neckarsulm//BlaBla" immer als "Kaufland" angezeigt wird, die ursprünglichen Daten aber trotzdem irgendwie erhalten werden.

Implementierung: Filter die beim CSV Import laufen und diese Daten ersetzen oder ergänzen. (Ich find die Information, dass es in Neckarsulm war, nicht ganz verkehrt, aber meistens will ichs nicht sehen.)

Später: Irgendwann könnte man sogar solche Filterlisten vordefinieren, sodass der normaler Nutzer nicht selbstständig diese eintragen muss. Dann sind normale "bekannte Firmen" vorgekürzt.

/idee

**Comment by Tosh79** [comment]
Hallo @cassava ,
vielen Dank für den Vorschlag. Ich werde das auf jeden Fall im Hinterkopf behalten, wenn ich mich an das Ding hier setze... schöner Nebeneffekt einer solchen Integration wäre natürlich, dass die Umsatzzuordnung wahrscheinlich noch besser funktionieren würde. Dann wäre es *lamonee nämlich egal, ob Du bei Esso Nürnberg oder Esso Hamburg tankst...
