### ISSUE TITLE
Buchungen mehreren Budgets zuordnen

### ISSUE THREAD

**Issue by swantjej** [Tosh79/lamonee_backlog#606]
Bei YNAB kann man Kontobuchungen mehreren Budgets zuordnen (dort "Category split"). Wir brauchen so etwas regelmäßig um bei budgetübergreifenden Einkäufen in größeren Märkten Posten wie z.B. "Einkäufe/Haushalt", "Haustiere" und "Garten" auseinander zu trennen.

**Comment by Tosh79** [comment]
Hallo @swantjej , das geht auch jetzt schon bei *lamonee. Wähle dazu einfach in der Kategorieauswahl eines Umsatzes den Punkt "Mehrere Budgetposten" (gaaaaanz unten in der Liste!): dann kannst Du Deinen Umsatz beliebig vielen Budgetposten zuweisen:

![Screenshot 2021-11-07 171954](https://user-images.githubusercontent.com/40628353/140653144-dc7a6724-eabb-4379-bebf-80e107cb77b4.jpg)

LG
Tobias

**Comment by swantjej** [comment]
Vielen lieben Dank Tobias, das habe ich tatsächlich total übersehen. Sorry für die Umstände!

LG,
Mareike


Am 7. November 2021 17:17:50 MEZ schrieb Tosh ***@***.***>:
>Hallo @swantjej , das geht auch jetzt schon bei *lamonee. Wähle dazu einfach in der Kategorieauswahl eines Umsatzes den Punkt "Mehrere Budgetposten" (gaaaaanz unten in der Liste!): dann kannst Du Deinen Umsatz beliebig vielen Budgetposten zuweisen.
>
>
>
>LG
>
>Tobias
>
>
>
>-- >
>You are receiving this because you were mentioned.
>
>Reply to this email directly or view it on GitHub:
>
>https://github.com/Tosh79/lamonee_backlog/issues/606#issuecomment-962639386
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Tosh79** [comment]
Hallo @swantjej , alles gut! Mach bloß weiter so! Dafür ist das Ding hier auch gut! Ich wünschte, andere Anfragen würden sich auch so schnell in Wohlgefallen auflösen ;-)
