### ISSUE TITLE
Not able to install PWA on Android

### ISSUE THREAD

**Issue by natrius** [Tosh79/lamonee_backlog#607]
Servus, ich hoffe, ich darf hier einfach ein issue aufmachen. 

Device: Xiaomi Mi 9
Android: 10

Und zwar bekomm ichs nicht gebacken, die App als PWA zu installieren. Ich habs einmal probiert mit Firefox Daylight (?) 93.1.0, über das Share-Symbol kommt kein "Au den Desktop" oder etwas ähnliches. 
Über Fennec 94.1.1 hab ichs dann auch noch probiert und nicht hinbekommen. Dann mal die Addons wie HTTPS Everywhere, privacy badger und ublock origin deaktiviert, keine Änderung. Irgendwie kam dazwischen mal doch ein PopUp mit "Wollen sie Lamonee zum Startbildschirm" hinzufügen, wo ich natürlich "JA" angedrückt habe, hat aber nix geholfen. Leider kein Lamonee am Desktop :(

Dann habe ich mal in Fennec den Cache gelöscht und jetzt habe ich sowas wie ne bootloop auf der Webseite auf app.lamonee.de/#/#/logout sieht zwar amüsant aus, ist aber nervig. Switched zwischen "Dein Budget wird geladen" und "Erste Budgetkategorie anlegegen" mit "Ein Standardbudget starten" herum. Grob 0,5 - 1 Sekunden-Takt, relativ nervig. Ich lass das jetzt mal in dem Status, falls du noch eine Info brauchst.

Ich hab dann interessehalber noch https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs und https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen überflogen und laut zweitem Link: Magst nicht vielleicht in den Settings oder so einen Button einbauen für Leute, die so unfähig sind, wie ich? :p

EDIT: https://www.lamonee.de/lamonee-als-app-installieren/ hab ich mir durchgelesen, "Weitere tools" gibts unter Firefox aber leider nicht. "Add to top sites" hat mir nix gebracht, "Bookmarken" auch nicht und bei "Teilen" gibts eben kein "Auf den Desktop teilen" oder so.

**Comment by Tosh79** [comment]
Hallo @natrius ,
das hört sich ja nicht so toll an. So wie's aussieht, sollte(!) es eine "Install"-Option in Firefox Daylight geben (siehe auch: https://support.mozilla.org/bm/questions/1347501).  Wie's mit Fennec aussieht, weiß ich leider nicht. Aber insgesamt steht Mozilla dem Thema "PWA" leider etwas zwiespältig gegenüber, was man daran erkennen kann, dass der PWA-Support für die Firefox Desktop-Version gekippt wurde.... schade!

Nichtsdestotrotz habe ich mir einmal den "Boot-Loop-des-Todes" (TM) angesehen und ich hoffe(!!), dass ich einen Fix integrieren konnte, der jetzt auch schon live ist. Bitte leere noch ein letztes Mal Deinen Browsercache und probiere es noch einmal aus. 

Viele Grüße!
Tobias

**Comment by natrius** [comment]
Kanns sein, dass da was fehlt oder so? Das hätt ich sofort gedrückt :D 

 
![IMG_20211109_215035](https://user-images.githubusercontent.com/7243447/141003174-d7824b2c-962a-4582-8cd1-3c4c3ff4c061.jpg)

**Comment by Tosh79** [comment]
Oha! Ja, dann scheint da etwas bei Dir zu fehlen :D Die von mir verlinkte Anfrage ist immerhin gut 2 1/2 Monate alt - vielleicht hat sich da schon wieder etwas getan... Chrome zu verwenden ist keine Option für Dich? Da funktioniert das nämlich Sahne...!

**Comment by natrius** [comment]
FYI: das scheint am Launcher zu liegen, bei mir "OpenLauncher". Suuuper *seufz*

https://github.com/OpenLauncherTeam/openlauncher/issues/522

**Comment by natrius** [comment]
Nein, Google macht das Internet kaputt, da will ich nicht wirklich unterstützen. :)

**Comment by Tosh79** [comment]
Okay, das kann ich verstehen :)
Dann heißt es wohl leider "Abwarten und Tee trinken" 🍵

**Comment by Tosh79** [comment]
Achja: @natrius wie sieht's denn mit dem Bootloop aus? Das müsste doch jetzt funktionieren, oder? ODER?

**Comment by Tosh79** [comment]
Einen hab ich noch: https://github.com/Tosh79/lamonee_backlog/issues/610

**Comment by natrius** [comment]
@Tosh79 Ganz vergessen, ja, sieht gut aus, ich habe keine Bootloop mehr erhalten. 

Und, 610 sieht auch gut aus :) Cool. Ich geh mich mal nach nem anderen Launcher umsehen :p
