### ISSUE TITLE
Neuer Auftraggeber kann (manchmal) nicht angelegt werden

### ISSUE THREAD

**Issue by drcollatz** [Tosh79/lamonee_backlog#613]
Beim Erfassen eines neuen Umsatzes kann ich aktuell keinen neuen Auftraggeber eintragen. Die Validierung schlägt fehl mit dem Hinweis "Bitte gib mindestens zwei Zeichen ein" obwohl ein Text mit mehr als zwei Zeichen eingetragen wurde. 
Allerdings hat es zwischendurch doch mal funktioniert. Also ein sporadischer wenn auch derzeit sehr häufiger Fehler. 
Mit Chrome und Safari auf MacOS gleiches Verhalten.

![Auftraggeber Fehler](https://user-images.githubusercontent.com/9221406/141663153-9f048157-9008-43a1-84cb-298537b64cd5.png)

**Comment by Tosh79** [comment]
Hallo @drcollatz , danke für Meldung! Schaue ich mir sehr zeitnah an!

LG
Tobias

**Comment by drcollatz** [comment]
> Hallo @drcollatz , danke für Meldung! Schaue ich mir sehr zeitnah an!
> 
> LG Tobias

Hi Tobias,
Ok, vielen Dank. Ich habe eben sogar den gesamten Browsercache gelöscht, den *lamonee Acc. zurückgesetzt und mit einem neuen Konto ganz fresh versucht einen Umsatz zu erfassen. Leider ging das ebenfalls nicht. "zeitnah" wäre spitze, da *lamonee aktuell so für nicht verwendbar ist :-/

PS.:
Ich freue mich schon sehr darauf nYNAB den Rücken zu kehren und ab 1.1.2022 mit *lamonee durchzustarten 👍 
LG,
Paul

**Comment by Tosh79** [comment]
Hi @drcollatz , ich HOFFE (tm), dass ich einen Hotfix für das Problem finden konnte. Gerne 1x ausprobieren. Mir ist das Problem seitdem nicht mehr untergekommen...!

**Comment by drcollatz** [comment]
Sieht sehr gut aus! Danke für den ultra schnellen Fix 👍
