### ISSUE TITLE
Falsche Umsatzanzeige, wenn die Summe der Buchungen auf einen Budgetposten Null ergibt

### ISSUE THREAD

**Issue by drcollatz** [Tosh79/lamonee_backlog#622]
Wenn ich eine Buchung mit bspw. +50€ und eine Buchung mit -50€ auf die gleiche Kategorie / Budgetposten mache, steht im Monatsbudget bei der entsprechenden Umsatz Spalte (kleine Lupe) -> Keine Umsätze zugeordnet

![keine Umsätze bei Summe 0](https://user-images.githubusercontent.com/9221406/145710976-b4c376e9-e443-49e4-aebe-f3aea061f983.png)

**Comment by Tosh79** [comment]
Hi @drcollatz ,

vielen Dank für Meldung dieses Bugs! Ich kümmere mich darum!

LG
Tobias

**Comment by Tosh79** [comment]
Das Thema scheint lange behoben.
