### ISSUE TITLE
Passwortvergabe: Punkt und Komma werden nicht als Sonderzeichen erkannt

### ISSUE THREAD

**Issue by SCORP111** [Tosh79/lamonee_backlog#623]
Moin,

wenn man sich registriert und als Sonderzeichen z.B. ein . oder , verwendet, wird weiterhin angezeigt, dass man kein Sonderzeichen im Passwort hat (rotes x). Man kann sich aber trotzdem registrieren. Ein ! oder - im Passwort führt aber dazu, dass ein grüner Haken bei Sonderzeichen angezeigt wird.

Gruß

**Comment by Tosh79** [comment]
Hi! Vielen Dank für die Meldung! Punkt und Komma werden sehr bald als Sonderzeichen erkannt!

**Comment by Tosh79** [comment]
Übrigens: dass man sich trotzdem registrieren kann, ist beabsichtigt!
