### ISSUE TITLE
Fehlerhafter Datenimport DKB Kreditkarte

### ISSUE THREAD

**Issue by MoriarT3a** [Tosh79/lamonee_backlog#652]
Beim importieren einer csv-Datei ist mir ein Fehler aufgefallen.
Alle Umsätze, die in der csv ohne ein Komma angegeben sind, werden nicht als Euro, sondern als cent Beträge importiert.

Beispiel:

<table class="tg">
<thead>
  <tr>
    <th class="tg-za14">Umsatz abgerechnet   und nicht im Saldo enthalten</th>
    <th class="tg-za14">Wertstellung</th>
    <th class="tg-za14">Belegdatum</th>
    <th class="tg-za14">Beschreibung</th>
    <th class="tg-za14">Betrag (EUR)</th>
    <th class="tg-za14">Ursprünglicher Betrag</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">Ja</td>
    <td class="tg-za14">30.03.2022</td>
    <td class="tg-za14">29.03.2022</td>
    <td class="tg-za14">COMMERZBANK ATM</td>
    <td class="tg-za14">-100</td>
    <td class="tg-0pky"></td>
  </tr>
  <tr>
    <td class="tg-0pky">Ja</td>
    <td class="tg-za14">28.03.2022</td>
    <td class="tg-za14">27.03.2022</td>
    <td class="tg-za14">Amazon.deAMAZON.DE</td>
    <td class="tg-za14">-13</td>
    <td class="tg-0pky"></td>
  </tr>
  <tr>
    <td class="tg-0pky">Ja</td>
    <td class="tg-za14">07.02.2022</td>
    <td class="tg-za14">06.02.2022</td>
    <td class="tg-za14">SpotifyStockholm</td>
    <td class="tg-za14">-14,99</td>
    <td class="tg-0pky"></td>
  </tr>
  <tr>
    <td class="tg-0lax">Ja</td>
    <td class="tg-7zrl">07.02.2022</td>
    <td class="tg-7zrl">05.02.2022</td>
    <td class="tg-7zrl">Jack Wolfskin Retail GmbHIdstein</td>
    <td class="tg-7zrl">-417,9</td>
    <td class="tg-0lax"></td>
  </tr>
</tbody>
</table>

Reihe 1 und 2: Für die Barabhebung werden 1,00 € und für die Zahlung an Amazon 0,13 € importiert. Richtig wären 100€ und 13,00 €.
Da scheint der Importer das Komma falsch zu setzen.
Bei Reihe 3 ist der Import mit 14,99 € korrekt.
Bei Reihe 4 ist wieder der Kommafehler vorhanden. Hier wurden beim Import 41,79 € draus.

Edit:
Weiterer Fehler, aber wohl auf Basis der selben Ursache hinzugefügt. (Reihe 4)

**Comment by Tosh79** [comment]
Hallo @MoriarT3a ,
vielen Dank für die Meldung! Ich schau' mir das sehr zeitnah an!
LG
Tobias

**Comment by Tosh79** [comment]
Hallo @MoriarT3a ,
ich habe mir das Thema gerade einmal angesehen. Rein zufällig bin ich selber DKB Kunde und hab mir mal aus erster Hand den Export angesehen. Bei mir werden im Export die "Nullen" angehängt. Bei mir wird also nicht "-100" angezeigt, sondern "-100,00". 

Hast Du eventuell Deine Export-Datei im Nachhinein bearbeitet? In diesem Fall können nämlich Tabellenkalkulationen wie Excel, Numbers und OpenOffice auf die nicht-so-sinnvolle Idee kommen, Deine Nummernformate vollkommen ungefragt zu ändern.

Idealerweise probierst Du einmal aus, einen Export aus DKB direkt und ohne Umwege vom DKB Online Banking gen *lamonee zu importieren. Also ins DBK-Banking rein, exportieren, auf'm Desktop speichern. Und anschließend, ohne die Datei vorher mit irgendetwas zu öffnen, nach *lamonee zu importieren...

Wenn der Fehler immer noch auftritt, sprechen wir noch einmal. Ich habe mitbekommen, dass DKB ja gerade alle Karten konsolidiert - vielleicht gibt's da ja auch ein neues Online-Banking?

LG
Tobias

**Comment by MoriarT3a** [comment]
Hallo @Tosh79 ,
ich habe wohl wirklich die Datei vorher geöffnet und unbedacht neu gespeichert. Wenn ich die *.csv ohne vorheriges öffnen importiere, funktioniert alles wie es soll.
Wenn ich die Datei mit Notepad++ öffne, sind auch die beiden Nachkokmmanullen da. Excel zeigt sie zwar nicht an, aber wenn ich die Datei nicht bearbeite/speichere funktioniert der Import auch.

Kurzum: Alles funktioniert. Danke!

Entschuldige bitte den "Fehlalarm"


Viele Grüße
Hendrik

**Comment by Tosh79** [comment]
Alles gut! Ich bin froh, dass es kein "echtes" Problem mit *lamonee ist. Wenn Dir noch mehr auffällt, freue ich mich über weitere Issues!

LG
Tobias
