### ISSUE TITLE
Wiederholende Transaktionen

### ISSUE THREAD

**Issue by Ctrl-A-Del** [Tosh79/lamonee_backlog#656]
Ich konnte bisher keine Möglichkeit finden, eine Transaktion einzurichten, die sich jeden Monat am selben Tag wiederholt. Bei den Konten, wo noch kein CSV-Import unterstützt wird würde diese Funktion das manuelle Eintragen von Transaktionen sehr vereinfachen.

**Comment by Tosh79** [comment]
Hallo @Ctrl-A-Del ,
vielen Dank für Deine Anfrage, mit der Du nicht alleine stehst. Es gibt bereits ein Ticket dazu, wo ich alle Anfragen sammele: https://github.com/Tosh79/lamonee_backlog/issues/411 . Ich schließe deshalb dieses Ticket hier.

Nur noch so viel: prinzipiell möchte ich eine solche Funktion einbauen, es kann aber noch etwas dauern, bis es soweit ist. Wenn Du noch weitere Anmerkungen zu der Funktion hast, bitte unter #411 posten.

Vielen Dank und beste Grüße
Tobias
