### ISSUE TITLE
Neuer Importer: Solarisbank

### ISSUE THREAD

**Issue by paaxnt** [Tosh79/lamonee_backlog#657]
Hallo Tobias Schirski,

ich nutze die App seit eben und wechsle von der YNAB App zu dir und bin bisher sehr begeistert wie viel Herzblut du reinsteckst. Danke für die bisher schon großartige App.

Kannst du bitte auch die Solarisbank in den Importer aufnehmen?

LG!

**Comment by Tosh79** [comment]
Hallo @paaxnt ,
vielen Dank für die Blumen. Bitte verzeih, dass ich mich jetzt erst zurückmelde. Ich bin umgezogen. Wenn Du mir einen Beispielexport der Solarisbank an hallo@lamonee.de schickst, kann ich Dir einen Importer ziemlich schnell zusammenbauen. Welche Banken aktuell unterstützt werden und wie die Beispieldatei idealerweise aussieht, findest Du hier: https://www.lamonee.de/unterstuetzte-banken/

LG
Tobias

**Comment by Tosh79** [comment]
Export erhalten. Eingeplant.
