### ISSUE TITLE
Budget umgestaltet, plötzlich zu viel Budget

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#667]
Sollte eigentlich nicht passieren. Muss ich mal überprüfen.

**Comment by Tosh79** [comment]
> Genau genommen müssen wir das korrigieren: es wurden keine Buchungen gelöscht, sondern wir haben Kategorien gelöscht und andere neu angelegt. Wir haben das noch vorhandene Budget der alten Kategorien vorher auf die neuen Kategorien umgelagert. In den gelöschten Kategorien war kein Budget mehr vorhanden, sodass jeweils 0 € in das Gesamtbudget zurück transferiert wurden. Diese Meldung wurde auch angezeigt. 
> 
> Durch diese Umschichtungen hat sich ein immer größeres, freies Budget in unserer Ansicht angehäuft. Obwohl unsere Konten jetzt alle den richtigen Betrag aufweisen, scheinen wir deutlich mehr Geld zur Verfügung zu haben. Das kann nicht stimmen (auch wenn es schön wäre). 
>

**Comment by Chrysadelic** [comment]
Hallo Tobi,
ich habe heute ebenfalls Budgetposten und Kategorien gelöscht (Budgetposten standen jeweils auf 0), auf denen in den vergangenen Monaten Posten gebucht wurden. Nun habe ich ebenfalls einen falschen Plusbetrag als übriges Budget von über 1500 Euro und zusätzlich ist auch die Kontensumme zerschossen und weicht um 5000 Euro ab. Ich weiss grade auch nicht so recht, mit welchem Trick ich das wieder gradebiegen kann. Ich habe veruscht, die 1500 Euro manuell auf ein Falschberechnungskonto zu buchen, das resettet mir zwar den Monat wieder, aber die Kontensumme ist immer noch falsch. Ich stehe hier auch gerne zur Analyse zur Verfügung, wenn du was brauchst.
LG, Chris

Edit: Wenn ich mir die vorherigen Monate anschaue, hat jeder Monat, der eine von der Löschung betroffene Buchung hatte, ein Problem mit der Summe, teils im Plus, teils im Minus.

Edit 2: Wenn ich die nicht mehr zugeordneten Beträge verändere, verändert sich auch das übrige Budget. Ordne ich es zu, steigt das übrige Budget, nehme ich die Zuordnung wieder raus, sinkt es wieder. Es bleibt aber in beiden Fällen jeweils falsch.

**Comment by Tosh79** [comment]
Hallo @Chrysadelic ,
puh, das hört sich jetzt natürlich nicht so toll an. Es tut mir leid, dass Du gerade so einen Struggle mit *lamonee hast.
Ich hab jetzt die letzten 1-3 Stunden damit verbracht, einen vergleichbaren Testfall herbeizuführen. Also eine Situation, wo ich Dinge budgetiere, Ausgaben erfasse, diese dann Budgetposten zuweise und dann den ganzen Kladderadatsch lösche.

In keinen Fällen konnte ich ein Verhalten von *lamonee beobachten, dass mir fehlerhaft oder willkürlich erschien. Alle Ergebnisse konnte ich mir erklären.

Mein Hauptfinding zuallererst:
**Ja**, es kann sein, dass das Löschen eines Budgetposten einen durchaus bleibenden Eindruck  im Gesamtbudget hinterlässt. Und das ist schlecht und für mich ein Hauptgrund, das Archivieren von Budgetposten noch auf meine Märzagenda zu packen.

Bevor ich in die Details gehe, möchte ich kurz zusammenfassen, wie *lamonee mit gelöschten Budgetposten umgeht:
1. Wird ein Budgetposten gelöscht, dem Negativ-Umsätze zugeordnet waren, so werden diese Negativ-Umsätze dem Gesamtbudget abgezogen - ganz so, als seien die Umsätze nie zugewiesen worden.
2. Wird ein Budgetposten gelöscht, dem Positiv-Umsätze zugeordnet waren, so werden die Positivbeträge UNTER UMSTÄNDEN dem Gesamtbudget zugeordnet und zwar wie folgt:

Gehen wir davon aus, dass ein Budgetmonat mehrere Nicht-Zugeordnete Umsätze hat.
- die Summe der nicht-zugeordneten Negativ-Umsätze beläuft sich auf -300 Euro
- die Summe der nicht-zugeordneten Positiv-Umsätze beläuft sich auf 200 Euro.
- Folglich wird dem Gesamtbudget ein Betrag von -100 Euro abgezogen. Der Teil, der NICHT von den Positiv-Umsätzen abgedeckt wurde. Die positiven Umsätze haben also direkt Einfluss auf das Gesamtbudget.

Anderes Beispiel:
- die Summe der nicht zugeordneten Negativ-Umsätze beläuft sich wieder auf -300 Euro
- die Summe der nicht zugeordneten Positiv-Umsätze beläuft sich aber diesmal auf 500 Euro.
- In diesem Fall verändert sich das Gesamtbudget ÜBERHAUPT NICHT! Warum? Die 500 Euro "neutralisieren" den negativen Einfluss der -300 Euro auf das Gesamtbudget. Der Betrag, der darüber hinaus geht (200 Euro) MUSS MANUELL als Einkommen verbucht werden, bzw. einem Budgetposten zugeordnet werden. Damit möchte *lamonee erzwingen, dass diese sehr wichtigen Umsätze entsprechend kategorisiert sind. Und in den letzten Jahren hat das eigentlich auch immer ganz gut geklappt.

Aber die Länge dieses Texts zeigt mir, dass das womöglich nicht besonders intuitiv ist, wenn man's beschreiben muss. Unter der Haube funktioniert diese Herangehensweise super, führt aber zu schwer verständlichen Ergebnissen, wenn bestehende Posten gelöscht werden. Deshalb meine Entscheidung, die Archivierungsfunktion asap einzubauen.

So, aber was kannst DU jetzt tun, um Dein Budget wieder glatt zu bekommen? Ich würde Dir raten, auch wenn's weh tut, mindestens die POSITIVEN Umsätze, die nach der Löschung keinem Posten mehr zugeordnet sind, wieder einem Posten zuzuordnen, oder als Einkommen zu verbuchen. Nur so wirken sie sich auch auf's Budget aus. 

Gib' mir dann gerne Rückmeldung, ob und wie das geklappt hat!

LG
Tobias

**Comment by Chrysadelic** [comment]
@Tosh79 
Danke für das Feedback.
Ich werde das mit den positiven Umsätzen probieren.
Eine Sache ist mir noch aufgefallen:
Wenn ich einen alten, nicht mehr zugewiesenen Umsatz zuweise, bekomme ich immer unten am Bildschirm diese Meldug:


![Image](https://user-images.githubusercontent.com/55179477/222360998-652f5c90-a51b-40a0-8ac1-4ef9048e4759.png)

"Es gab einen Fehler bei der Daten-Aktualisierung: Network Error".
Also wirklich immer, sowohl in meinen Versuchen gestern als auch heute.

LG,
Chris

**Comment by Chrysadelic** [comment]
kurzes Feedback zu meinem Test:
Alle Einnahmen zugeordnet, damit steigen komischerweise beide falschen Werte (Kontostand und zu budgetierender Monatssaldo) noch.
Auch wenn ich jetzt alle Sätze, plus wie minus, zuordne, sind die Werte noch falsch.

LG,
Chris

**Comment by Tosh79** [comment]
Hallo @Chrysadelic ,
Uah, das ist natürlich nicht so gut. Vielleicht müssen wir mal eine Live-Session machen, wo Du mir das mal zeigen kannst. Also ganz besonders abgefahren finde ich, dass die Budgetzuweisungen sich auf den Kontostand der Konten auswirken. Das dürfte wirklich, wirklich nicht sein. Wenn Du Lust und Zeit hast, könnten wir ja eine kurze Remote-Session via Hangouts oder Teams starten. Schick mir gerne ne Termineinladung an hallo@lamonee.de!

**Comment by Chrysadelic** [comment]
Hallo @Tosh79,

ich kann das grad gar nicht mehr rekonstruieren, welche Transaktionen jetzt welche Budgetbewegung auslösen. Ich bekomme den Betrag auch nicht mehr passend. 
Siehst du auf Datenbankebene, ob da Werte in der Berechnung nicht mit reinzählen? Vielleicht geht da aber auch einfach aufgrund des Network Errors irgendwas schief, was schlicht die Aktualisierung unterbindet?
Remote Session wird diese Woche eng, Arbeit und kranke Kinder machen mir da nen Strich durch die Rechnung. Ich bekomme wie gesagt auch gar keine Rekonstruktion des Phänomens mehr hin. Das einzige was sich reproduzieren lässt, ist der Network Error wenn ich ein älteres Budget mit gelöschtger Position neu zuweise.

**Comment by Tosh79** [comment]
Hallo @Chrysadelic ,
ja hm. Also ich werde mir das noch einmal auf Datenbankebene ansehen. Es kann durchaus sein, dass die Network-Errors eine mögliche Ursache sein können, dass das Frontend falsche Zahlen ausspuckt. Im Backend sollte trotzdem korrekt gerechnet werden. Was mir bei einer kurzen Übersicht Deines Budgets (bei der alle Budgetposten verschlüsselt sind, ich kann nix sehen) ist mir aufgefallen, dass Du verdammt viele Budgetposten hast. Es kann sein, dass das eine Ursache für den Netzwerkfehler sein kann. Wenn man einen Split-Umsatz aktualisiert, werden alle Umsätze, Budgets und Budgetposten aktualisiert. Es KANN sein, dass das etwas zu viel für das Backend ist. Sollte das noch einmal vorkommen, probiere doch bitte einmal folgendes aus: lade die Seite neu. Ohne jetzt den Monat zu wechseln & Co, öffne direkt den gewünschten Split-Umsatz und pflege noch einmal die gewünschten Werte. Evtl. nur mal eine Zuweisung hinzufügen. Dann Speichern. Seite neu laden. Hat das funktioniert? Dann eine weitere Zuweisung hinzufügen, etc. Bis es entweder geklappt hat, oder wieder auf die Nase gefallen ist. Sag mir bitte im letzteren Fall Bescheid, wie viele Split-Zuweisungen Du ausprobiert hast.

Danke für Deine Geduld und Mithilfe!
Tobias

**Comment by Tosh79** [comment]
Womöglich war #680 die Ursache für das Problem. Aktuell erhalte ich keine Meldungen mehr. Deshalb schließe ich dieses Ticket jetzt erst einmal.
