### ISSUE TITLE
Bug: Sparziel "Meine monatliche Sparrate" wird fälschlicherweise als "0" angezeigt

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#677]
Wenn ich ein Ziel habe, um Geld X zu sammeln, sollte eigentlich die monatliche Sparrate im *charm angezeigt werden. Wird sie aber nicht.
Zusätzlich #547 beachten.

**Comment by Tosh79** [comment]
Ah! Das liegt daran, dass ich einen Budgetposten im Juni 2020 geöffnet hatte, wobei das Sparziel in August 2022 war.

**Comment by Tosh79** [comment]
Trotzdem noch einmal prüfen:
Was passiert, wenn das Sparziel > X Jahre entfernt liegt?

**Comment by sclaren** [comment]
Ich kann den Fehler bestätigen. Sparziel mit Start Januar 23 und Ende Januar 24 zeigt hier als Summe 0 an

**Comment by Tosh79** [comment]
DONE
