### ISSUE TITLE
Mehrere Budgetposten funktionieren nicht (mehr)

### ISSUE THREAD

**Issue by Geda173** [Tosh79/lamonee_backlog#711]
Moin,

in der Vergangenheit hat das Zuweisen einer Buchung zu mehreren Budgetposten super funktioniert. Seit einigen Monaten passiert nach Eingabe aller erforderlichen Daten nichts mehr. Die Eingabe wird zwar angenommen nach klick auf den Haken bei Umsatz erfassen, danach passiert aber nichts. Die eben eingegebenen Daten tauchen nirgends auf und die Budgets werden nicht belastet. Neuladen der Seite lässt die Posten auch nicht auftauchen.

Getestet habe ich es mit Brave (Chromium) und dem Internet Explorer. Bei beiden Browsern tritt das Problem auf.

**Comment by Tosh79** [comment]
Hallo @Geda173 ,
oh, das ist schlecht! Ich werds mir ansehen! Danke für's melden!

LG
Tobias

**Comment by hexaholic** [comment]
Ich habe das selbe Problem. Exakt das selbe Verhalten habe ich damals bei https://github.com/Tosh79/lamonee_backlog/issues/680 beobachtet, und der CORS Fehler taucht jetzt auch wieder in der Browser-Konsole auf.

`Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.lamonee.de/api/transactions. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). Statuscode: 500.`

**Comment by Tosh79** [comment]
Hallo @Geda173 und @hexaholic , 
ich habe gerade einen Hotfix eingespielt. Bitte probiert einmal aus, ob Splitumsätze wieder funktionieren. Bei mir war's der Fall!

Vielen Dank für Eure Geduld und LG
Tobias

**Comment by Geda173** [comment]
Kurzer Test am Handy eben hat ergeben, dass es wieder funktioniert. Vielen Dank!
