### ISSUE TITLE
Postbank-Importer aktualisieren?

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#713]
Nutzer*in klagt darüber, dass der Postbank Importer nicht mehr funktioniert. Prüfen!

**Comment by Yomedrath** [comment]
zukünftiger Nutzer bestätigt das Fehlerhafte verhalten mit einem Screenshot
![grafik](https://github.com/Tosh79/lamonee_backlog/assets/60345534/d56aeca8-a2d9-44a8-9756-3f4d285a2224)

**Comment by Tosh79** [comment]
Hey @Yomedrath , alte Hippe! Schön, dass Du dabei bist! Magst Du mir eventuell über die Dir bekannten Wege eine NICHT NACHBEARBEITETE (!!) CSV-Datei zusenden? Es reicht, wenn da 1-2 Umsätze zu finden sind - idealerweise ein positiver, ein negativer und einer, aus dem ich ersehen kann, wie die Tausendertrennzeichen gehandelt werden. Alternativ kannst Du letzte Information auch gerne so mitteilen - Du weißt ja, worauf ich so achten muss.

Dann passe ich den Importer im Nullkommanix an!

LG
Tobias
