### ISSUE TITLE
Export des Monatsbudgets

### ISSUE THREAD

**Issue by elpiecho** [Tosh79/lamonee_backlog#714]
Ich würde gern die Monatsansicht als CSV exportieren können. Also in der Monatsansicht einen Button der eine CSV Datei mit den Spalten:

-Name (des Postens)
-Monatsanfang
-Bugetiert
-Verfügbar 
-Verfügbar zum Monatsanfang (Monatsanfang + Budgetiert)

erzeugt.

Hintergedanke ist, dieses Budget dann z.B. in eine Bankingsoftware zu importieren.

**Comment by Tosh79** [comment]
Das ist ein Duplikat von #664 . Ich habe Deinen Kommentar dort hinzugefügt.
LG
Tobias
