### ISSUE TITLE
 Kassenbonerkennung per Fotoscan

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#72]
> Kassenbonerkennung per Fotoscan :)

**Comment by natrius** [comment]
Vielleicht kann man da irgendwie mit der OpenSource App "OpenScan" https://github.com/Ethereal-Developers-Inc/OpenScan was machen?

**Comment by Tosh79** [comment]
Hi @natrius , spannender Input, vielen Dank! Soweit ich weiß, gibt es auch direkt APIs im Netz, an die man ein Foto schicken kann und die Dir dann die Ergebnisse liefern. Das würde den Umweg für die App ersparen... in jedem Fall bin ich an dem Thema noch dran! Danke!
