### ISSUE TITLE
YouTube: Wieso es keine gute Idee ist, negative Budgetposten in den Folgemonat mitzunehmen

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#735]
Als Follow-Up von #369

**Comment by ToxSox** [comment]
Ich hoffe es wird in dem Video drauf eingegangen, wie man damit umgehen kann, wenn man jemanden etwas vorstreckt.

**Comment by Tosh79** [comment]
Hallo @ToxSox ,

absolut: das ist, glaube ich, auch eines der gängigsten Szenarien für eine solche Situation!

LG
Tobias

**Comment by ToxSox** [comment]
Hallo @Tosh79 ,
fast ein Jahr ist herum und ich habe weiterhin genau mit diesem Thema zu kämpfen. Jetzt gerade hatte ich erst wieder den Fall, dass ich Reisekosten für meinen Arbeitgeber vorstrecken musste und die Ausgleichszahlung erst im darauf folgenden Monat kam.
Da erinnerte ich mich an das Thema. Es wäre SUPER, wenn du hier etwas zu erzählen würdest.

**Comment by Tosh79** [comment]
Na eventuell setze ich #369 doch einmal um.
