### ISSUE TITLE
Budget wird nicht aktualisiert

### ISSUE THREAD

**Issue by Malldond** [Tosh79/lamonee_backlog#767]
Zieht man das aktuelle Monatssaldo auf einen negatives Budget zum Ausgleich, wird zwar der Budgetposten ausgeglichen, das Monatssaldo bleibt scheinbar jedoch erhalten. Beispiel: Haushalt -300 €, Saldo: 200 € vor Ausgleich.
Nach Ausgleich: Haushalt 0,00 €, Saldo 200 €.

**Comment by Tosh79** [comment]
Hallo @Malldond ,
vielen Dank für die Meldung! Tatsächlich verhält sich *lamonee an dieser Stelle korrekt. Denn der Budgetüberzug ist bereits in dem Monatssaldo mit "eingepreist". Bedeutet, dass es für das Monatssaldo keinen Unterscheid macht, ob ein Budgetposten überzogen ist, oder ob Du Geld aus dem Monatssaldo entnimmst, um einen überzogenen Budgetposten auszugleichen. Wenn Du auf Dein Monatssaldo klickst, findest Du eine Detailansicht der einzelnen Zu- und Abläufe.

Wenn Dich das Thema interessiert, dann empfehle ich Dir meine kleine YouTube-Tutorial-Reihe. Es folgt ein Link, wo ich genau dieses Thema beschreibe:
https://www.youtube.com/watch?v=z4c8eR8hQ1g&t=223s

Dieses Ticket hier mache ich dann einmal zu!

Viele Grüße!
Tobias
