### ISSUE TITLE
Anmerkung zu Budgeteintrag hinterlassen

### ISSUE THREAD

**Issue by Tosh79** [Tosh79/lamonee_backlog#79]

**Comment by Tosh79** [comment]
> Kommentare zu Kategorien wären top

**Comment by Tosh79** [comment]
> Auf Anhieb vermisse ich jedoch die &quot;Notiz&quot;-Funktion von YNAB, sprich für jeden Posten ein Freitextfeld allgemein und zusätzlich pro Monat am budgetierten Wert.
> Nutze ich dort als Kommentar um später noch zu wissen, wenn ich etwas abweichend budgetiert hab, z.B. Umschichten von einem Sparziel auf ein anderes.

**Comment by Tosh79** [comment]
Der Kommentar sollte unabhängig vom Monat sein. Und eine Textarea sein.

**Comment by Tosh79** [comment]
> Ich habe zum Beispiel einen Posten "Onlinedienste". Da würde ich gerne notieren welche Dienste das zurzeit umfasst,
> 
> Also eine einfache Textnotiz wie:
> 
> Netflix 11,99€ (monatlich)
> Spotify 9,99€ (monatlich)

**Comment by Tosh79** [comment]
> Kategorien mit Notizen versehen zu können ist für mich ein essentielles Feature. 

> Ich möchte z.B. einen Budgetposten "Onlinedienste" haben und da dann z.B
notieren woraus sich das monatliche Budget für diesen posten zusammensetzt.

**Comment by drcollatz** [comment]
Eine Möglichkeit für Notizen bei Budgetposten wäre ein Traum. Ich hatte da bei YNAB sehr wertvolle Infos stehen, die ich beim Umstieg leider nirgends pflegen kann ;-(
